### ISSUE TITLE
Truncate large payloads to ensure we don't drop them

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/Rollbar.NET#105]

**Comment by rokob** [comment]
So in the Gem, near the end of payload processing, pretty much right before sending the payload to the API, we possibly apply a series of transformations depending on the size of the payload. The code the runs this is here: https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/truncation.rb. We keep trying more aggressive truncation techniques until the payload is below 512kb.

The first strategy is to do nothing, called the raw strategy in the gem. This is the normal case as most payloads do not need to be truncated.

Then, we proceed to the frames strategy (https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/truncation/frames_strategy.rb) which reduces the total number of frames in the trace to some limit (2*N) by keeping the first N frames and the last N frames and dropping the middle frames. In Ruby the default N value is 150, but this could be much smaller here.

If that does not reduce the payload enough, then we try the strings strategy (https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/truncation/strings_strategy.rb) which attempts to limit all value strings to a fixed byte size to reduce the overall payload below the threshold. It does this in steps from 1024, then 512, and finally 256 bytes. We basically take the payload and iterate over all key/value pairs, if the value is a string and it is larger than the truncation limit, then we replace the string with the beginning of the string up to the byte limit plus an ellipsis to indicate that it was truncated.

Finally, if we are still over the total payload limit, we use the min body strategy (https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/truncation/min_body_strategy.rb) which basically throws out everything but the most important data. We attempt to send this final payload no matter what.
