### ISSUE TITLE
Notifier does not send Exception.Data collection

### ISSUE THREAD

**Issue by chuchuva** [rollbar/Rollbar.NET#118]
Exception.Data is collection of key/value pairs that provide additional user-defined information about the exception.

Repro:

            try
            {
                throw new System.NotImplementedException("oops");
            }
            catch (System.Exception ex)
            {
                ex.Data["Temperature"] = 24;
                RollbarLocator.RollbarInstance.Error(ex);
            }

Open error in Rollbar website.

Observe: Temperature custom field is not present.
Expected: Temperature custom field should be present.

**Comment by akornich** [comment]
Meanwhile, following should do the trick:

        try
        {
            throw new System.NotImplementedException("oops");
        }
        catch (System.Exception ex)
        {
            var data = new Dictionary<string, object>();
            data["Temperature"] = 24;
            RollbarLocator.RollbarInstance.Error(ex, data);
        }

We will definitely add an auto-"snapping" of Data property from an exception object as well. Stay tuned.

**Comment by akornich** [comment]
The Data auto-capture is implemented in my fork:
[https://github.com/WideSpectrumComputing/Rollbar.NET](url)
If anyone interested to give it a try before the official release, you are welcome!

When you log something like:

            Dictionary<string, object> customFields = new Dictionary<string, object>();
            customFields.Add("Hebrew", "אספירין");
            customFields.Add("Hindi", "एस्पिरि");
            customFields.Add("Chinese", "阿司匹林");
            customFields.Add("Japanese", "アセチルサリチル酸");
            customFields.Add("path1", "d:\\Work\\\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\\branches\\v2\\...");
            customFields.Add("path2", @"d:\Work\אספירין\branches\v2\...");

            var exceptionWithData = new ArgumentNullException("Exception with Data");
            exceptionWithData.Data["argumentName"] = "requiredOne";
            RollbarLocator.RollbarInstance.Error(exceptionWithData, customFields);

the result would look like that in the Rollbar Dashboard:

![image](https://user-images.githubusercontent.com/1753993/38759052-c058bfa8-3f28-11e8-88fa-cbf5d024d4be.png)
