### ISSUE TITLE
Exception running integration tests

### ISSUE THREAD

**Issue by patoncrispy** [rollbar/Rollbar.NET#119]
I'm trying to run integration tests in .NET Core using `Microsoft.AspNetCore.TestHost.TestServer`. I'm initialising the `TestServer` with my application's `Startup` class that runs perfectly both in Development and Production environments without problems. 

However, I keep getting the following exception.
```
An error occurred while writing to logger(s). (Object reference not set to an instance of an object.)
   at Rollbar.AspNetCore.RollbarHttpAttributes..ctor(HttpContext context)
   at Rollbar.AspNetCore.RollbarLogger.GetCurrentContext()
   at Rollbar.AspNetCore.RollbarLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
```

My `IWebHostBuilder` loads my user secrets, add I've debugged my `Startup` class and it startups fine.
This is how my `IWebHostBuilder` is made:

```
private IWebHostBuilder CreateBuilder()
        {
            return new WebHostBuilder()
                .UseContentRoot(Path.GetFullPath(@"../../../../../src/Project"))
                .UseEnvironment("Development")
                .ConfigureAppConfiguration((builderContext, config) =>
                {
                    config.AddUserSecrets<Startup>();
                })
                .UseStartup<Startup>();
        }

```

Is there anything particular that I might have to configure differently to get Rollbar to work in this context?

**Comment by akornich** [comment]
@patoncrispy , let me guess. are you using pre-1.2.0 release of Rollbar.Net? if my guess is correct, please, move to 1.2.0

**Comment by akornich** [comment]
@patoncrispy , would you like to try my latest fork?
[https://github.com/WideSpectrumComputing/Rollbar.NET](url)
I think it should unblock you until the next package release.

**Comment by patoncrispy** [comment]
Thanks @akornich. I just tried it out. I'm still getting a `NullReferenceException`, but this time it's on `RollbarMiddleware.Invoke(HttpContext context)` and for some reason `context` is null.

**Comment by akornich** [comment]
@patoncrispy, thanks for trying it out. i just added handling of uninitialized context object. it should be good now in my fork.
however, it does seem odd to have a middleware component invoked with undefined http context. here is from microsoft documentation:
"What is middleware?
Middleware is software that's assembled into an application pipeline to handle requests and responses. Each component:
- Chooses whether to pass the request to the next component in the pipeline.
- Can perform work before and after the next component in the pipeline is invoked."

When http context is not initialized, what request are we processing then? :)

**Comment by akornich** [comment]
@patoncrispy, yes that is what i am thinking, too. btw, did the latest code change in my fork unblock you?

**Comment by patoncrispy** [comment]
Sorry for the late reply, @akornich, but yes, I'm unblocked now. Thank you!

**Comment by akornich** [comment]
@patoncrispy, thanks for the feedback. just to make sure you did not miss it, Rollbar.NET v1.2.1 is out and has this problem's fix in it.

**Comment by patoncrispy** [comment]
Ace. Have updated NuGet package and can confirm all is well.

**Comment by akornich** [comment]
@patoncrispy, thanks for the feedback!
