### ISSUE TITLE
Add custom fingerprinting (similar to other SDKs)

### ISSUE THREAD

**Issue by akornich** [rollbar/Rollbar.NET#120]

**Comment by akornich** [comment]
it seems to me that the most logical way, in my opinion, for custom fingerprint calculation would be to have it as (or as part of) the custom defined Transform custom defined delegate. But that would mean we do not have to do anything for this work item, except maybe updating the docs with this recommendation.
@rokob is on board with this.

**Comment by rivkahstandig3636** [comment]
Great, let's just update the docs then.
