### ISSUE TITLE
Capture local variables

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/Rollbar.NET#124]
Similar to pyrollbar. See 'locals' here: https://docs.rollbar.com/docs/python#section-configuration-reference

**Comment by akornich** [comment]
No capturing fram's local variables yet. At least we could not find out proper .NET API for that yet. However we are adding object state capture capabilities. For example, capture like this one:

`public void DemonstrateStateCapture()
            {
                var criticalObj = new InstanceType();
                criticalObj.AutoProperty = -100;

                try
                {
                    ///...
                    /// oh, no - we have an exception:
                    throw new System.Exception("An exception with state capture!");
                    ///...
                }
                catch (System.Exception ex)
                {
                    // capture state of this instance:
                    var state = RollbarAssistant.CaptureState(this, "Self"); 
                    // also, capture state of some other critical object:
                    state = new Dictionary<string, object>(state.Concat(RollbarAssistant.CaptureState(criticalObj, nameof(criticalObj))));
                    // also, capture current state of a static type:
                    state = new Dictionary<string, object>(state.Concat(RollbarAssistant.CaptureState(typeof(StaticType))));

                    // report the captured states along with the caught exception:
                    RollbarLocator.RollbarInstance.AsBlockingLogger(TimeSpan.FromMilliseconds(10000)).Error(ex, state);
                }
            }`

would produce following log on the Rollbar API service side:

![image](https://user-images.githubusercontent.com/1753993/40522631-b7e749f6-5f86-11e8-9662-d344757cbd3d.png)
