### ISSUE TITLE
Add capture uncaught config option

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/Rollbar.NET#125]
Similar to rollbar.js, the ability to turn on/off uncaught error reporting. (This isn't properly documented currently but this section of the docs talks about it: https://docs.rollbar.com/docs/javascript#section-angular-2-and-later)

**Comment by akornich** [comment]
As a reference from JS SDK docs:

Setting the captureUncaught option to true will result in reporting all uncaught exceptions to
Rollbar by default.

**Comment by akornich** [comment]
i guess this one is only applicable to asp.net core middleware component of Rollbar.NET SDK...
