### ISSUE TITLE
Add max items config option

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/Rollbar.NET#126]
Similar to rollbar.js maxItems: https://docs.rollbar.com/docs/javascript#section-global

**Comment by akornich** [comment]
@rivkahstandig3636 and @jessewgibbs , the JS SDK documentation states:

maxItems
Max number of items to report per page load. When this limit is reached, an additional item will be reported stating that the limit was reached. Like itemsPerMinute, this limit counts uncaught errors (reported through window.onerror) and any direct calls to Rollbar.log/debug/info/warning/error/critical().
Default: 0 (no limit)

I guess for .NET it will be "per HTTP request". Correct?

**Comment by jessewgibbs** [comment]
@akornich I'd say tentatively yes to "per HTTP request", but I'd like to get confirmation from @rokob and @rivkahstandig3636 .  Also, @ArturMoczulski may be able to share some insights about how he's planning to do this for PHP and Ruby.

**Comment by ArturMoczulski** [comment]
@akornich PHP is going to be very straightforward. I will add a static variable to the `Rollbar` class to keep the track of sent items and add a logic gate to stop sending when the threshold is met. PHP is NOT multithreaded, so this naive solution is fine.

I'm not sure if you have to take into consideration thread safety in Rollbar.NET, but in Ruby that will be the case. Also, in Ruby, there might be cases where the process will stay alive throughout multiple requests. To summarize, both in Ruby and .Net we need to consider:

1. Thread safety
2. Processes that stay alive between multiple requests.
