### ISSUE TITLE
Anonymize IP address config option

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/Rollbar.NET#130]
We need to allow users the option of collecting IP addresses and anonymizing them. Let's anonymize the IPs as described here: https://support.google.com/analytics/answer/2763052

@akornich  This is a top priority.

**Comment by akornich** [comment]
@rivkahstandig3636,  i guess, taking in account issue #129 and in order to make it more straightforward for the users we can introduce an enumeration like IPAddressCollection with following members: Collect, CollectButAnonymize and DoNotCollect. Shall we go with this approach?

**Comment by akornich** [comment]
@rivkahstandig3636, for example, in scenario when a user configures CollectButAnonymize for the IPAddressCollection setting, than any time within the SDK we capture any IP address we anonymize it right away. I assume, we also want to search for the same (not-yet-anonymized) IP address instances within every reported exception stacks/messages and anonymize them (or completely mask them out in case of DoNotCollect) as well. Correct? What if users report their own IP address explicitly as part of informational log entry or a custom field, do we anonymize/mask-out these instances as well?

**Comment by rivkahstandig3636** [comment]
As long as Collect is the default, that's fine with me. If users report an IP address as part of a log entry or custom field, that should be covered under scrubbing I believe. @jessewgibbs What are your thoughts on this?

**Comment by jessewgibbs** [comment]
@rivkahstandig3636 I agree with your proposal.  If an IP address is sent elsewhere in the payload due to a custom configuration, it should be scrubbed separately from the default IP address value.

**Comment by rivkahstandig3636** [comment]
Great, thanks! @akornich Let me know if you have any further questions :)
