### ISSUE TITLE
System.TypeInitializationException exception

### ISSUE THREAD

**Issue by VicZhang1** [rollbar/Rollbar.NET#147]
Hello,

I am using Rollbar.NET 1.4.0, when I try to 
`RollbarLocator.RollbarInstance.Info(ex, customData);`

then I get:
```
System.TypeInitializationException:
   at Rollbar.DTOs.Body..ctor (Rollbar, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null)
   at Rollbar.RollbarLogger.Error (Rollbar, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null)
   at Rollbar.RollbarLogger.Rollbar.ILogger.Error (Rollbar, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null)
```

Can anyone help me?

Thanks
-
Vic

**Comment by VicZhang1** [comment]
I tried all versions which are higher than v1.1.1, only v1.1.1 works for me, looks strange.

**Comment by akornich** [comment]
@VicZhang1, are you calling RollbarLocator.RollbarInstance.Info(...) or RollbarLocator.RollbarInstance.Error(..)? The call stack shows Error(...) call.
What platform are you running on .NET Framework or .NET Core or Xamarin? What OS?

**Comment by VicZhang1** [comment]
Hi @akornich , thanks for your reply. I am using it as
`RollbarLocator.RollbarInstance.Error(ex, customData);`

By the way, I am using Rollbar in Azure Function instance, but I can reproduce this on my Windows 10 PC.

This error occurred when I upgraded Rollbar 1.1.1 to 1.4.0. I also tried 1.2.0/1.3.0, the error still occurred on those versions. Once I use back to 1.1.1, all is fine.

**Comment by akornich** [comment]
@VicZhang1, the exception comes from Body.cs (the best we know for now). Body.cs was touched last in December 2017.  v1.1.1 was released in the end of March 2018. It has to be something else, especially looking at the type of exception. So, are you running it in .NET Core environment? What version? Do you get any package compatibility warnings when building your solution?
Can you repro it in debug builds? Try setting "break on the  exception type source" in VS (Exception Settings) and repro it. That may give us more clues.

**Comment by VicZhang1** [comment]
Hi @akornich , looking into the InnerException, message is
`Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`

StackTrace:
```
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Rollbar.Utils.ReflectionUtil.GetSubClassesOf(Type baseType)
   at Rollbar.DTOs.DtoBase.ReflectStringProperies()
   at Rollbar.DTOs.DtoBase..cctor()
```

**Comment by VicZhang1** [comment]
```

  | Name | Value | Type
-- | -- | -- | --
▶ | [0] | {"Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.":"Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"} | System.Exception {System.IO.FileNotFoundException}
```

**Comment by VicZhang1** [comment]
I am using Newtonsoft.Json 11.0.2, looks like you also reference Newtonsoft.Json 10.0.3.

**Comment by VicZhang1** [comment]
With the same settings/dependencies, I just downgrande Rollbar from 1.4.0 to 1.1.1, all works fine. I am strange that why Rollbar 1.1.1 works with Newtonsoft.Json 11.0.2 well but 1.4.0.

**Comment by akornich** [comment]
@VicZhang1, now it makes sense. We used to keep Rollbar.NET dependencies updated to the latest available. Until we hit this one: #90 
That is when we pinned Newtonsoft.Json to v10 (by dropping down from v11 that was causing #90).
I quess Azure Functions were recently updated to use v11.
We can bump it back up to v11 next release (most likely upcoming Monday next week).
@VicZhang1, for now you can clone rollbar.net source code from github and modify the dependency to v11 and rebuild and use this private build until the release.

**Comment by akornich** [comment]
@VicZhang1 , v1.5.0 is out. However, I did not have to change any Newtonsoft.Json dependency settings. The one we currently have means that any version of the dependency that is >=10.0.3 is allowed. Please, make sure your deployment does indeed have Newtonsoft.Json of at least v 10.0.3
