### ISSUE TITLE
Document individual functions

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/Rollbar.NET#16]
From internal issue tracker:
> Currently no inline documentation. Go through and document everything with MS Standard XML docs.
> Make sure the docs come through in Visual Studio when installed from NuGet

**Comment by rokob** [comment]
We need this

**Comment by akornich** [comment]
All the inline documentation on public types and type members should be already in v1-alpha.

**Comment by akornich** [comment]
I just enabled XML documentation file generation for all configurations and all targeted .NET platforms in v1.

**Comment by akornich** [comment]
Currently available in:
[https://github.com/WideSpectrumComputing/Rollbar.NET/tree/v1](url)
