### ISSUE TITLE
AspNetCore2.WebApi _logger.LogError(exception, "bla"); doesn't send the exception to rollbar

### ISSUE THREAD

**Issue by michaeljfarr** [rollbar/Rollbar.NET#165]
The NET core RollbarLogger ignores the exception detail if a log message is provided. So, if I call _logger.LogError(e, "Bla"); somewhere in my app, the details in the exception do not come through to rollbar. 

It seems there is no perfect answer to this problem, so I thought I'd ask for your opinion.  First, some background:
The .NET core logger extensions provide a message formatter by default, which accepts the message and the exception, but never returns any information from the error. The rollbar logger seems to assume that the formatter combines the exception and the message together somehow. There has been some discussion on ASPNETs github and one person says "Ultimately, the formatter should be ignored in most cases as reasonable loggers will use the exception argument passed in." (https://github.com/aspnet/Logging/issues/675). Although, I haven't read much more into it than that.

Is this something you are aware of? Would you be willing to change the logger to ignore the formatter and combine the exception and the message into the body sent to Rollbar?  Is there another solution to this problem that I am not aware of (for the moment, I am just putting the exception directly into the message string).

**Comment by akornich** [comment]
@michaeljfarr , thanks for reporting the issue. I was not aware of this problem until now. I'll be looking into a solution for it this week.
Also, we had somewhat similar issue when, in one specific scenario, an exception was not rendered properly within a Rollbar payload object and was reported to Rollbar as a text message instead. It is fixed in v1.5.1 release of Rollbar.NET SDK and is currently available under GitHub releases of the SDK (but not published on NuGet yet).

**Comment by michaeljfarr** [comment]
Hi.  is interesting about that other issue.  I was trying to understand how/if the SDK handles having a string message and an Exception at the same time.  There doesnt' seem to be a suitable constructor on the Body class.  I had a look at the other Dto classes but couldn't see how it should be done.  Thanks for looking into it ;-)

**Comment by akornich** [comment]
it was a use case when client code was calling an API that returned an exception as an object. then, the client code was passing it into the RollbarLogger's Log method overload that accepts an object to log. the method used to just call ToString() on the passed object and subsequently reporting it as a message. we added type discovery to the method to handle objects more intelligently: 
[https://github.com/rollbar/Rollbar.NET/commit/7b6ec39a87a6bfd4c44fc6d680bec58da1b47688](https://github.com/rollbar/Rollbar.NET/commit/7b6ec39a87a6bfd4c44fc6d680bec58da1b47688)

**Comment by akornich** [comment]
@michaeljfarr , i wanted to address here one of your questions that i missed:
Rollbar API accepts payloads with body DTOs that must have following mutually exclusive contents:
- trace (for reporting exceptions without inner ones)
- trace_chain (for reporting exceptions that contain inner exception(s) )
- message (free formed textual messages)
- crash_report (i believe this one is applicable to Apple platform only)
Current Body DTO design reflects this behaviour.
Whenever ASP.NET Core Logger logs an exception with additional message we need to compile a payload Body based on the exception and add custom attribute to the payload carrying the body with the extra custom attribute representing the additional message (the custom attribute name is LogMessage). In this case the exception will be properly interpreted on the Rollbar API side and the additional message will be presented properly (as a custom attribute associated with the reported entry).
I already have a fix and currently testing it. It will show up today in Wide Spectrum Computing fork.

**Comment by michaeljfarr** [comment]
Thanks very much.  That was a really fast turnaround, and it works great!

**Comment by akornich** [comment]
@michaeljfarr, thanks! Please, feel free to submit new feature and improvement requests. 
Best regards,
- Andrey
