### ISSUE TITLE
Convenience methods for Logging erroneously using Error LogLevel

### ISSUE THREAD

**Issue by david-s-svedberg** [rollbar/Rollbar.NET#169]
The implementation (`RollbarLogger`) of
`ILogger Warning(Exception error, IDictionary<string, object> custom = null);`
calls `Report` using `ErrorLevel.Error`:

```
public ILogger Warning(System.Exception error, IDictionary<string, object> custom = null)
{
	this.Report(error, ErrorLevel.Error, custom);

	return this;
}
```
The same is true for the `Info` and `Debug` methods. This makes the messages show up as Errors instead of their appropriate Level in the Dashboard.

**Comment by david-s-svedberg** [comment]
I'm trying to create a fix but having some issues setting up my environment, trying to resolve...

**Comment by david-s-svedberg** [comment]
First time contributing on github, please let me know if there's anything else I need to do.

**Comment by akornich** [comment]
@david-s-svedberg, the PR looks good. Thank you! Merging it in...
