### ISSUE TITLE
Upgrade to 1.4.0 caused lot of errors

### ISSUE THREAD

**Issue by smakol** [rollbar/Rollbar.NET#174]
We started receiving lot repeated errors in Rollbar when we upgraded the .net version from 0.3.2 to 1.4.0.

This was the error  "**API error: Invalid format. data.body.trace_chain[2].frames is missing and it is required.**" Upon looking further we noticed that Rollbar was getting errors in malformed JSON.

Total occurrence of this error was 931,418 in three days. The error stops when we recycle the app pool in IIS but restarts again.

**Comment by akornich** [comment]
@smakol , please, try using the latest release and if the issue is still reproducible, please, subscribe to the InternalEvent of the RollbarQueueController singleton and capture the payload that it was trying to transmit when it was rejected.
