### ISSUE TITLE
Add example showing local variables

### ISSUE THREAD

**Issue by mostlyjason** [rollbar/Rollbar.NET#178]
The marketing team would like an example demonstrating the use of local variables that we can use for screenshots in our product SDK page. Since the .NET SDK does not support local variables, it looks like fields from objects on the stack are populated into parameters. the current unit test uses field names that are very abstract and may be difficult for customers to intuitively grasp.

https://rollbar.com/Rollbar/Rollbar.Net/items/305/occurrences/46404627126/?offset=0&sort=last_desc&status=&level=&query=&assigned_user=&framework=&environment=&date_from=&date_to=&activated_from=&activated_to=&timezone=America%2FLos_Angeles&project_ids=

Can you please create a unit test or example with a more intuitive example, such as a simple to-do list, pet store, etc. We'd like someone looking at a screenshot of these parameters to immediately grasp their purpose without much explanation.

**Comment by rivkahstandig3636** [comment]
Great idea @mostlyjason!
