### ISSUE TITLE
Send additional data about HTTP request

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/Rollbar.NET#18]
details in https://app.clubhouse.io/rollbar/story/13915

**Comment by rokob** [comment]
The details basically say that we should support customizing:

- endpoint (url we post to)
- headers
- user agent

Also we should support sending the client ip if there is one. This is something that we should do, and will add to the v1 milestone.

**Comment by akornich** [comment]
@rokob : do we already have payload fields that have to be populated with this matadata?

**Comment by rokob** [comment]
There is an optional `request` key in the payload body, https://rollbar.com/docs/api/items_post/ 
<img width="652" alt="screen shot 2017-12-01 at 11 47 14 am" src="https://user-images.githubusercontent.com/831355/33500379-780d862e-d68d-11e7-91b6-a2f5ab7623bd.png">

**Comment by akornich** [comment]
@rokob, thank you!
We already have have a DTO for the Request data object in v1-alpha where the following fields can be fill out by the client:
`        public static class ReservedProperties
        {
            public const string Url = "url";
            public const string Method = "method";
            public const string Headers = "headers";
            public const string Params = "params";
            public const string GetParams = "get_params";
            public const string QueryString = "query_string";
            public const string PostParams = "post_params";
            public const string PostBody = "post_body";
            public const string UserIp = "user_ip";
        }
`
Does it mean we can call it done?

**Comment by akornich** [comment]
@rokob : "body" object has "platform" property. we currently specify "windows" as its value. Shouldn't it have ".NET" value since it can run on either Windows, or Mac, or Linux? And then we can use "framework" property to specify actual .NET implementatio (core2.0 or full4.6, etc.)?
