### ISSUE TITLE
Allow proxy credentials in proxy server configuration

### ISSUE THREAD

**Issue by lennyefkc** [rollbar/Rollbar.NET#186]
I'm in a corporate environment where we need to use an egress proxy for all outgoing Internet requests. But not only is proxy usage required, we also need to use credentials to authenticate with the proxy. 

Would you please support configuring proxy authentication credentials into the WebProxy object you use?

Thanks!

**Comment by akornich** [comment]
@lennyefkc, i think we can do that. meanwhile, please, try NOT setting any proxy setting explicitly on rollbar object (in code or via configuration), but instead using following block in your app.config or web.config file:
<system.net>
    <defaultProxy useDefaultCredentials="true">
      <proxy proxyaddress="proxyAddress" usesystemdefault="True"/>
    </defaultProxy>
  </system.net>

Please, let me know if it unblocks you for now.

**Comment by akornich** [comment]
Adding ProxyUsername and ProxyPassword properties to RollbarConfig. These properties are also supported within app.config appsettings.json as proxyUsername and proxyPassword fields.

**Comment by lennyefkc** [comment]
@akornich, thank you so much for the quick action on this! I'll pass it along to our team.

Cheers!
-Lenny
