### ISSUE TITLE
Unicode characters serialized incorrectly

### ISSUE THREAD

**Issue by coryvirok** [rollbar/Rollbar.NET#19]
At least 1 rollbar customer is seeing unicode escape characters in the payload reported by Rollbar.NET. 

E.g. 
```
"...{"filename":"d:\\Work\\\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\\branches\\v2\\..."
```

It appears that this SDK is serializing unicode into ascii which results in the unicode escape sequences making their way into the payload. It should be serializing into ascii with UTF-8 encoding.

**Comment by rokob** [comment]
We should definitely handle serialization of UTF-8 correctly, adding to the v1 milestone.

**Comment by akornich** [comment]
i look into this one after we close unit test coverage and documentation tasks of the second phase of v1 development.
we are using Newtonsoft.Json serialization library. it probably has to do with making some tuning there to handle the encoding properly.

**Comment by akornich** [comment]
for the future reference:
[](https://stackoverflow.com/questions/21498090/convert-json-unicode-to-utf8)

**Comment by PantelisAr** [comment]
Hey guys, is this fixed in v1.0.1?

**Comment by akornich** [comment]
Most likely today there will be a check in that switches use of WebClient to HttpClient. It has explicit settings for UTF8 encoding. It may just unblock this issues. However, we did not specifically test that this is the case. But I can probably do this today including a follow up fix if necessary...

**Comment by akornich** [comment]
the latest codebase seem to handle unicode properly. Examples are added to the sample console app.
