### ISSUE TITLE
Which token to use for wpf/winform app

### ISSUE THREAD

**Issue by amiram** [rollbar/Rollbar.NET#218]
In the setup instructions of winform app, the sample uses the server token instead of the client token. Is it a mistake? When I add a new token, it appears that the client token is for: "Allows access to POST client-side items (platform is android, browser, client, flash, or ios)". Isn't a winform app considered as client platform?

**Comment by amiram** [comment]
Another problem in the sample. This code can't compile:
`Rollbar.Init(new RollbarConfig...`
since Rollbar is the namespace name.

It should be as the .NET server sample:
`RollbarLocator.RollbarInstance.Configure(new RollbarConfig(...));`

**Comment by jessewgibbs** [comment]
Hi @amiram.  You're correct that a Winforms app requires a server-side token, but arguably it could use a client-side token instead.

As for the example, can you tell us the URL where you found that?

**Comment by amiram** [comment]
https://github.com/rollbar/docs/pull/260

**Comment by jessewgibbs** [comment]
@amiram thanks for the docs update.  I'm going to submit a feature request for our app team to allow use of client-side tokens with Winforms apps.
