### ISSUE TITLE
Research CI service alternatives

### ISSUE THREAD

**Issue by akornich** [rollbar/Rollbar.NET#236]

**Comment by akornich** [comment]
Travis - does not seem to support .NET Framework on Windows builds
CircleCI - same as Travis.
Azure Pipelines - claims to support all the current .NET implementations as targets.

**Comment by jessewgibbs** [comment]
@akornich does Azure Pipelines look like the best CI choice so far?

**Comment by akornich** [comment]
@jessewgibbs , yes, Azure Pipelines does look like a very good option. I already prototyped its integration for CI builds (a release build + unit tests triggered by a GitHub commit) within my fork:
[https://github.com/WideSpectrumComputing/Rollbar.NET](https://github.com/WideSpectrumComputing/Rollbar.NET)
If you click the Azure Pipelines last build status badge, you get to the pipelines site. 
Azure DevOps also allows to add automated product release pipelines including publiching of product packages to NuGet.

**Comment by akornich** [comment]
resolved by PR#265
