### ISSUE TITLE
Redundant dependency for .NET Framework targets

### ISSUE THREAD

**Issue by bpashkovskyi** [rollbar/Rollbar.NET#247]
Looks like dependency to Microsoft.Windows.Compatibility in .Net Framework (4.5-4.7.2) targets is not required and can be removed to avoid tons of dependencies from Microsoft.Windows.Compatibility

**Comment by akornich** [comment]
@bpashkovskyi , correct, the compatibility pack should be conditioned to only non-Framework .NET implementations. Thanks for catching it. We will be adding the conditioning to the next upcoming release.
