### ISSUE TITLE
Missing web.config crashes RollbarConfig constructor method

### ISSUE THREAD

**Issue by Janek91** [rollbar/Rollbar.NET#254]
**Describe the bug**
In 2.1.1 version my WPF application crashes on creation of RollbarConfig instance.

 
**To Reproduce**
1. Create desktop application with following code on startup:

```
RollbarConfig config = new RollbarConfig(accessToken);
```
accessToken is string in GUID format.
2. Start application
3. Application crashes complaining about path format. In fact, due to code in GetAppConfigFileAlternatives() method of FileUtility class it's searching for web.config file, which is not present in desktop application.

**Expected behavior**
RollbarConfig instance is created without error

**Rollbar Client - Rollbar.NET Hosting Environment**
 - Rollbar.NET Host type: desktop app
 - OS and its version: Windows
 - .NET flavor and its version: .NET Standard 2.0
 - Application framework and its version: WPF
 - Rollbar.NET Version: 2.1.1

**Additional context**
Adding web.config file to application directory is preventing this exception.

**Comment by akornich** [comment]
@Janek91 , thanks for reporting the issue. I'll be looking into it shortly...

**Comment by akornich** [comment]
@Janek91 , i just added a sample solution of Rollbar.NET within a WPF app attempting to repro your use case scenario. it is available here:
[https://github.com/WideSpectrumComputing/Rollbar.NET/blob/master/Samples/Sample.WPF.sln](https://github.com/WideSpectrumComputing/Rollbar.NET/blob/master/Samples/Sample.WPF.sln)
It runs clean without any exception during the RollbarConfig instantiation and past that. Please, try it yourself and let me know if you are doing anything significantly different compering to this example.

**Comment by akornich** [comment]
Closing due to no repro and no responses from the issue originator...

**Comment by Janek91** [comment]
Yes. Couldn't reproduce issue after that. In 2.2.0 works good as well. Maybe some compilation glitch, as I'm using Costura.Fody to bundle everything in single exe file.

**Comment by akornich** [comment]
@Janek91 , thanks for the update!
