### ISSUE TITLE
PostBody is always null

### ISSUE THREAD

**Issue by Lobosque** [rollbar/Rollbar.NET#263]
**Describe the bug**
When using the Request DTO to send additional data, PostBody is always empty/null:
https://github.com/rollbar/Rollbar.NET/blob/725f08e1d1786514e8c9bda76c1be43d804bd32f/Rollbar/DTOs/Request.cs#L155

This seems to be related with the fact that you can only read the `Request.Content` once.

I have found some solutions to ASP.NET Core to add a rewind middleware so you are able to read the content more than once, but I haven't found any solution to "classic" .NET Framework 4.6 MVC project.

I am pretty new to the .NET landscape and am not sure how I can add a middleware to .NET Framework MVC or be able to read this data in any other way to send to rollbar.

**Comment by akornich** [comment]
@Lobosque, may I ask you to post a sample project with a repro of this issue?

**Comment by Lobosque** [comment]
@akornich hello,

I was able to work around the issue.

This happens when you use model binding in your controller actions.
Since the Content stream was already read and the pointer is currently at the end, it returns nothing when the line I pointed out is read.

in .NET Core this can be fixed by using a middleware called `EnableRewind`

In .NET Framework MVC this can be fixed by adding the following Message handler: (more about the solution here: https://stackoverflow.com/questions/12494067/read-httpcontent-in-webapi-controller):

```
internal sealed class BufferizingHandler : DelegatingHandler
{
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        await request.Content.LoadIntoBufferAsync();
        var result = await base.SendAsync(request, cancellationToken);
        return result;
    }
}
```

I am not sure what/how the library can be improved to avoid the problem. But I believe this is worth a mention in source code or even better: the docs.

**Comment by akornich** [comment]
@Lobosque , thanks for letting us know about this usage specifics.
That is what it looked like to me. That it is not directly an issue of Rollbar.SDK but a specifics of the ASP.NET MVC/Core architecture that requires a request content to be re-winded before each subsequent use - something to be handled on the application level and not within the Rollbar.NET (which is not only used within an ASP.NET apps but also within WPF, WindowForms, Xamarin, Mono based apps, etc.)
I'll see if we can add some kind of conditional rewind of the request content automatically when necessary.

**Comment by jessewgibbs** [comment]
@akornich should we update the docs to cover this usage scenario?

**Comment by akornich** [comment]
@jessewgibbs , it is a constrain of ASP.NET application architecture that assumes that an application built on that architecture reads the request content once and if it need to use the same content more than once it is the application responsibility to re-wind it. We probably can mention it as a side-note reminder. I'll do it before closing this issue.

**Comment by akornich** [comment]
#329

**Comment by akornich** [comment]
@Lobosque , did you have a chance to try v3.0.2? we made some improvement around the area of the code that has to do with capturing request content.

**Comment by akornich** [comment]
closing due to no responses
