### ISSUE TITLE
Please allow AppSettingsUtility to work for projects targeting .net full framework.

### ISSUE THREAD

**Issue by trygvelo** [rollbar/Rollbar.NET#293]
**Is your feature request related to a problem? Please describe.**
We are using .net standard configuration system in projects targeting .net full framework, f.ex. net461. It's a bad idea to limit full framework projects to work with the old app.config (system.configuration) only. Right now I load the appsettings.json and bind it to RollbarConfig manually, but using the AppSettingsUtility would be nice for a totally "out-of-the-box" solution

**Describe the solution you'd like**
Please allow the new .net standard configuration system to work by limiting the AppSettingsUtility to only build for NETCOREAPP || NETSTANDARD.

**Comment by jessewgibbs** [comment]
@akornich what do you think?

**Comment by akornich** [comment]
I am not sure if it will work under Full Framework. I think last time I tried to integrate is with Full Framework I could not find any support of the used API under Full Framework. I'll give it one more try and see.

**Comment by akornich** [comment]
Looks like I remembered correctly Full Framework does not support these APIs yet:

**Comment by akornich** [comment]
Unless we want to add our own manual implementation not based on .NET Standard APIs?

**Comment by akornich** [comment]
I guess I'll try to fit it into the upcoming release...

**Comment by Lechus** [comment]
Could improve further and add support to read from Config when appsetting.Development.json is used? Right now values are taken from appsettings.json?

**Comment by akornich** [comment]
@Lechus , that is a good feature to add. Thanks!
We are now in preparation for a new major release this week (v3 of the SDK). Once it is out of the door, I'll start working on these config additions.

**Comment by Lechus** [comment]
@akornich : Good news!
Will v3 help with using Rollbar as log4net appender in ASP.NET Core 2 in testing project?

**Comment by akornich** [comment]
@Lechus , what do you exactly mean by "help"? Rollbar already implements a plug-in as log4net appender.

**Comment by akornich** [comment]
@Lechus , would you like to elaborate a bit more on your last question? thank you!

**Comment by Lechus** [comment]
Found workaround to disable Rollbar as log4Net appender when running integration tests.

I am using:
Project: Asp.NET Core 2.1 + log4Net + Rollbar as log4net appender. (RollbarInit in Startup as in sample example)
Test: Integration tests (full startup), Rollbar is throwing errors with something: "likeMe".

If I will find spare time, would like to get something like passing a Rollback "mock" to Startup(?) so in Full integration tests - throw an error -> catched -> log.Error -> passed to Rollbar appender -> Assert.That(RollbarAsAppender.WasCalled, Is.True)

**Comment by akornich** [comment]
@Lechus , if in your integration tests you just want to verify that Rollbar was invoked when expected, you may want to use it configured with invalid access token and subscribe to its internal event that will be raised every time anything interesting happens within the Rollbar SDK, including a CommunicationErrorEvent (representing communication attempt to transmit data to Rollbar API that ended with an error - due to wrong access token).
Also, can you, please, post call stack of the exception you mentioned in your last message?
