### ISSUE TITLE
ASP.NET code middleware not reporting request data

### ISSUE THREAD

**Issue by moxplod** [rollbar/Rollbar.NET#329]
Using rollbar asp.net core middleware latest version in a new application. I can see the errors being logged but NO errors contain the request parameters. 
Specifically missing - Headers and Post body.

**Comment by akornich** [comment]
@moxplod , are we talking about one of the latest preview releases? Or pre-v3?

**Comment by moxplod** [comment]
Asp.net core v2.1

**Comment by akornich** [comment]
@moxplod , here is an example with headers based on the very latest Rollbar.NET v3.0.1-preview release:
[https://rollbar.com/Rollbar/Rollbar.Net/items/2285/occurrences/69104822560/](https://rollbar.com/Rollbar/Rollbar.Net/items/2285/occurrences/69104822560/)

**Comment by moxplod** [comment]
I cannot access that item. Are you saying that we should try using the preview version in prod?

**Comment by akornich** [comment]
@moxplod , the headers seemed to work fine in the latest preview, but i did add capture of the post body, which is available in my fork:
[https://github.com/WideSpectrumComputing/Rollbar.NET](https://github.com/WideSpectrumComputing/Rollbar.NET)
Please, feel free to try it. Let me now how it goes.
Next official release will have it included...

**Comment by brianr** [comment]
We plan to have a new release with a fix for this issue this week.

**Comment by akornich** [comment]
#263
