### ISSUE TITLE
Log4Net - Timeout

### ISSUE THREAD

**Issue by Lechus** [rollbar/Rollbar.NET#333]
ASP .NET Core MVC 2.1
current Rollbar nuget plus Rollbar log4Net
log4net.config as in sample Net Core log4net project

Error is called in debug mode for testing, so it has time to connect to API.

log4net:ERROR [RollbarAppender] ErrorCode: GenericFailure. Failed in DoAppend
System.TimeoutException: Posting a payload to the Rollbar API Service timed-out
   at Rollbar.RollbarLoggerBlockingWrapper.WaitAndCompleteReport(SemaphoreSlim signal)
   at Rollbar.RollbarLoggerBlockingWrapper.Report(Object dataObject, ErrorLevel level, IDictionary`2 custom)
   at Rollbar.RollbarLoggerBlockingWrapper.Log(Data data)
   at Rollbar.PlugIns.PlugInCoreBase.ReportToRollbar(Data rollbarData)
   at Rollbar.PlugIns.PlugInCore`2.ReportToRollbar(TPlugInEventData plugInEventData, TPlugInErrorLevel plugInErrorLevel)
   at log4net.Appender.AppenderSkeleton.DoAppend(LoggingEvent loggingEvent)

**Comment by akornich** [comment]
@Lechus , what version of Rollbar SDK are you using? 
in general, transmission timeout could happen if you have deep enough transmission queue, low enough transmission rate, and/or short enough timeout interval.
Default timeout is 3 sec. 
try setting up (in appsettings.json) queue depth of 2 and rate of 60 (instead of 30).

**Comment by Lechus** [comment]
Hi,

Looks , the issue was that I put Rollbar AccessToken into appsettings.Development.json, not the appsetting.json so it was not read. 

Why do you return Timeout instead of Auth error?

**Comment by akornich** [comment]
@Lechus , thanks for the update. I am glad it works for you.
RollbarLogger depends on networking/Internet connectivity and has built in retries. The blocking version either successfully delivers a payload to Rollbar API server or times-out. There could be a lot of different reasons for a given timeout - from basic networking connectivity outages and targeted service availability to local transmission queue "overpopulated" for given timeout value, to any internal SDK error that prevented transmission. From the logging API point of view a blocking logging operation either succeeds or times-out (for whatever reason). To find out more details about possible causes of a time-out you can monitor SDK internal events available for every IRollbar instance and globally via the RollbarQueueController.
