### ISSUE TITLE
Finalize the list of supported .NET platform multi-targets

### ISSUE THREAD

**Issue by akornich** [rollbar/Rollbar.NET#34]

**Comment by rokob** [comment]
This is done right in the readme?

**Comment by coryvirok** [comment]
@akornich - ping

**Comment by akornich** [comment]
i'll be working on it during this second phase. the multi-platform targeting settings go into the .proj file. The readme file just has brief notes and resources for declaring the supported platforms.

**Comment by akornich** [comment]
Here the list of currently supported .net framework targets:
netstandard2.0;
netcoreapp2.0;
net4.7.1;
net4.7;
net4.6.2;
net4.6.1;
net4.6;
net4.5.2;
net4.5.1;
net4.5
Anything older than these will require conditionally compile-able code changes .
@rokob, @coryvirok , @jessewgibbs : do we want to go that route?

**Comment by akornich** [comment]
closing it since there no objections/suggestions...
