### ISSUE TITLE
services.AddRollbarLogger does not exist in the latest release

### ISSUE THREAD

**Issue by moxplod** [rollbar/Rollbar.NET#345]
services.AddRollbarLogger in the latest nuget package 3.0.2
What are we supposed to replace it with?

![image](https://user-images.githubusercontent.com/4554395/54480911-ae612700-47eb-11e9-9a94-95d10328f233.png)

**Comment by moxplod** [comment]
Also - app.UseRollbarMiddleware(); does not exist anymore. Is there latest documentation on how to configure Rollbar for asp.net core with the latest release?

**Comment by akornich** [comment]
@moxplod , here are the detailed release notes explaining all the API changes introduced in v3:
[https://github.com/rollbar/Rollbar.NET/releases/tag/v3.0.2](https://github.com/rollbar/Rollbar.NET/releases/tag/v3.0.2).

From the notes:
"All the Asp.Net Core middleware related classes were moved to the new Rollbar.NetCore.AspNet module."

Just add a reference to the new Rollbar.NetCore.AspNet module (also available via NuGet) and one more namespace to `using`: `Rollbar.NetCore.AspNet`. That should unblock you...

Complete documentation is here:
[https://docs.rollbar.com/docs/dotnet](https://docs.rollbar.com/docs/dotnet)

**Comment by akornich** [comment]
@moxplod , you may also find it useful to look at Asp.Net Core sample that we have here:

**Comment by moxplod** [comment]
Ok - that nuget package solved it!
Thank you.
