### ISSUE TITLE
Rollbar.NetCore.AspNet.RollbarLogger: payload title changes

### ISSUE THREAD

**Issue by akornich** [rollbar/Rollbar.NET#348]
when packaging payload from Rollbar.NetCore.AspNet.RollbarLogger make sure payload title is set to:
- exception.Message when logging an exception
- the logged message when logging a message

**Comment by akornich** [comment]
#346

**Comment by jbwps** [comment]
I think it may be necessary to look at the inner exception message if the exception has been wrapped by the Rollbar middleware.

**Comment by akornich** [comment]
@jbwps , the inner exception is available within the same payload. Can you, please, elaborate on what you exactly mean?

**Comment by Daenero** [comment]
In this case user log message will be completely ignored. 
Maybe we can set payload title to exception.Message only if user log message was not presented?

I have an exception occurring on one of my environments. I have added additional try/catch to log exception with some metadata. But since I am sending exception, my message with metadata is ignored.

**Comment by akornich** [comment]
@Daenero , may I ask you to post your code snippet/sample repoducing the problem? I am not sure I fully understand specifics of your use case. Thanks!

**Comment by Daenero** [comment]
@akornich Yep, sure.
Here we have logs that are writing some error messages with and without exceptions.
![2019-05-15_17-55-28](https://user-images.githubusercontent.com/23149500/57785596-bb8e8980-773a-11e9-839f-9ec5dc550ea8.png)

And this is what we see on Rollbar.com
![2019-05-15_17-52-46](https://user-images.githubusercontent.com/23149500/57785668-dbbe4880-773a-11e9-938f-9f94c928dc33.png)

So if we have both Exception and user text, we see only exception.Message on Rollbar title.

**Comment by akornich** [comment]
@Daenero , thanks! I see. I the case when both the exception and the message passed to the logger at the same time, the outermost exception's Message property set as the payload title, the exception is captured as either trace or trace chain (when there are any inner exceptions), the custom message that is passed along with the exception is captured as part of the custom data of the payload under "LogMessage" key. When you look at the details of such payload occurrence on the Rollbar Dashboard, you will see all this data captured there.  So, when deciding what the title should be we give preference to the exception message as compare to the custom log message. But, the custom log message is still captured within the payload details. If you do not find the "LogMessage" data field within the payload custom details in the scenario you described we do have a bug.
You can see how the described above logic implemented right here:
[https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar.NetCore.AspNet/RollbarLogger.cs#L146](https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar.NetCore.AspNet/RollbarLogger.cs#L146)

**Comment by akornich** [comment]
@Daenero, I just ran our sample app that simulates the scenario you are describing here:
```
            try
            {
                int level = 0;
                this.FakeExceptionCallStack(ref level);
            }
            catch(Exception ex)
            {
                this._logger.Log(logLevel: LogLevel.Critical, exception: ex, message: "Got one!");
            }
```
and the "Got one!" message gets captured under custom.LogMessage field with the occurrence:
[https://rollbar.com/Rollbar/Rollbar.Net/items/2740/occurrences/77641313949/](https://rollbar.com/Rollbar/Rollbar.Net/items/2740/occurrences/77641313949/)
It also reflected on the list of occurrences:
[https://rollbar.com/Rollbar/Rollbar.Net/items/2740/?item_page=0&#instances](https://rollbar.com/Rollbar/Rollbar.Net/items/2740/?item_page=0&#instances)
So far, all looks good - by design. However, all the improvements suggestions are always welcome.

**Comment by Daenero** [comment]
@akornich Ok, thanks for update. Now I can see my messages on Rollbar.com.

The only *not obvious* thing for me now it that Rollbar group errors by title. 
And in this case it is expected, at least for me, to have grouping by user messages, since one Exception can occur in different parts of application.

But this is not related to this package, so I will investigate the best approach to use logging on my needs.

**Comment by akornich** [comment]
@Daenero, I am glad you are unblocked now.
Regarding the grouping: in general, the reported exceptions grouped based on their trace/call-stack details which are a truly unique signature of an exception. However, we do have some small percentage of over-grouping and under-grouping cases with our current grouping algorithm implementation and due to some occasional inconsistencies when reporting trace-chains. We are currently actively working on a big set of improvements in these areas and already have a very promising plan of action that will be implemented in the very near future (probably, somewhere within the next few weeks).

**Comment by akornich** [comment]
Looks like, there are no questions at this point. Closing...
