### ISSUE TITLE
HTTP requests not logged automatically when logging errors

### ISSUE THREAD

**Issue by beeradmoore** [rollbar/Rollbar.NET#354]
Possibly not a bug, maybe its my misunderstanding coming from Rollbar PHP. I am running Rollbar.NET (3.0.3) in a .NETCoreApp 2.1 ASP.NET project which is normally run on AWS Lambda, although for the following is running locally on macOS.

If make a test controller and have it log an error it doesn't bring in the HTTP request data however if I throw an exception and not catch it two items will be reported on Rollbar, both of which have the HTTP request data. I assumed because I added the middleware it'd list HTTP method, URI, query params, etc with my issue logged with Rollbar.

This is the current state of my Setup.cs

```
    private void ConfigureRollbar()
    {
        var rollbarConfig = new RollbarConfig("...");
        ...
        RollbarLocator.RollbarInstance.Configure(rollbarConfig);
    }


    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSingleton<Microsoft.AspNetCore.Http.IHttpContextAccessor, Microsoft.AspNetCore.Http.HttpContextAccessor>();

        ConfigureRollbar();

        services.AddRollbarLogger(loggerOptions =>
        {
            loggerOptions.Filter = (loggerName, loglevel) => loglevel >= LogLevel.Error;
        });

        services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        services.Configure<MvcJsonOptions>(options =>
        {
            options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
        });
    }


    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        if (env.IsDevelopment())
        {
           // app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseHsts();
        }

        app.UseRollbarMiddleware();

        app.UseHttpsRedirection();
#if DEBUG
        app.UseMiddleware<DeChunkerMiddleware>();
#endif
        
        app.UseMvc();

    }
```

And my test controller method looks like
```
    [HttpGet]
    [Route("/test/error")]
    public ActionResult<string> TestError()
    {
        RollbarLocator.RollbarInstance.AsBlockingLogger(TimeSpan.FromSeconds(5)).Error(new Exception("Test exception 1."));
        //throw new Exception("Test exception 2.");
        
        return Ok("Ok");
    }
```

When I access http://localhost:5000/test/error, it'd send additional details about my request through to Rollbar. Using `RollbarLocator.RollbarInstance.AsBlockingLogger` it does not log additional data. 

Straight up throwing the exception will send through both:
- (Critical) RollbarMiddleware processed uncaught exception.
- (Error) The included internal exception processed by the Rollbar middleware
items to be created which do contain header and other details I'd expect.

The critical error contains request
```
 "request": {
    "url": "localhost:5000/test/error", 
    "query_string": "?blah=123", 
    "params": null, 
    "method": "GET", 
    "headers": {
      "Connection": "close", 
      "Content-Type": "application/x-www-form-urlencoded; charset=utf-8", 
      "Host": "localhost:5000", 
      "User-Agent": "Paw/3.1.8 (Macintosh; OS X/10.14.4) GCDHTTPRequest"
    }
  }, 
```
in its item, whereas the error just as,
```
 "request": {
    "httpRequestTimestamp": "2019-03-31T14:34:19.089455+11:00", 
    "protocol": "HTTP/1.1", 
    "headers": {
      "Connection": "close", 
      "Content-Type": "application/x-www-form-urlencoded; charset=utf-8", 
      "Host": "localhost:5000", 
      "User-Agent": "Paw/3.1.8 (Macintosh; OS X/10.14.4) GCDHTTPRequest"
    }, 
    "url": "localhost:5000/test/error", 
    "httpRequestID": "0HLLLH711C2LF:00000001", 
    "params": null, 
    "query_string": "?blah=123", 
    "scheme": "http", 
    "method": "GET", 
    "statusCode": 200
  }
```

But the `.Error(` does not log any request data. 

Did I set something up wrong or is what I expected to happen not how the `.Error(` works?

**Comment by akornich** [comment]
@beeradmoore , thanks for providing good amount of details about the issue!
When you throw an uncaught exception it get processed by the RollbarMiddleware component that you activated by calling `app.UseRollbarMiddleware();`
The middleware caches all the metadata about an incoming http request and adds that metadata to a Rollbar payload if it catches any uncaught exception within the guarded middleware pipeline (while wrapping the original exception into a RollbarException).
When you directly call any of the RollbarLogger logging methods directly they only capture what you pass into the methods (and no extra metadata). If you catch an exception yourself within a controller and log it, you have an option of wrapping it into an HttpRequest package decorator using reference to the relevant HttpRequest instance, so that request details will be attached to the payload as well.
Here is an example of using package decorators:
```
              IRollbarPackage rollbarPackage = new ExceptionPackage(ex, $"{nameof(RollbarMiddleware)} processed uncaught exception.");
                        rollbarPackage = new HttpRequestPackageDecorator(rollbarPackage, context.Request, true);
                        RollbarLocator.RollbarInstance.Critical(rollbarPackage);
```

**Comment by beeradmoore** [comment]
Thanks for getting back so quick.

That makes perfect sense. I’ll update my code tomorrow and let you know how it goes.

**Comment by beeradmoore** [comment]
Thanks @akornich, that worked a treat.
