### ISSUE TITLE
AddRollbar() is missing in release 3.0.3

### ISSUE THREAD

**Issue by mregni** [rollbar/Rollbar.NET#355]
**Describe the bug**
Not sure if this is a bug or wanted behavior but when creating the WebHost in a dotnet CORE 2.2 app there was a AddRollbar() extention method and it is gone in the new release (3.0.2), is this on purpose or not? I checked the repo and the implementation is still in place. (Rollbar.NetCore.AspNet/LoggingBuilderExtensions.cs)

**To Reproduce**
1. Create dotnet CORE 2.2 app
2. Call ConfigureLogging() on your IWebHost
3. Call AddLoggbar() in the passed Action to ConfigureLogging()

**Screenshots**
![image](https://user-images.githubusercontent.com/22617019/55307374-aa720d80-5457-11e9-969f-2e203fbae81c.png)

**Rollbar Client - Rollbar.NET Hosting Environment (please complete the following information):**
 - Rollbar.NET Host type: web service
 - OS and its version: Windows 10, Version 10.0.17763 Build 17763
 - .NET flavor and its version: .NET Core 2.2.105 SDK
 - Application framework and its version: WebApi
 - Rollbar.NET Version: 3.0.3

**Additional context**
I think it has something to do with the `#if NETCOREAPP` because the target framework is changed from "netcoreapp2.2;netcoreapp2.1;netcoreapp2.0" to "netstandard2.0". If I open the LoggingBuilderExtensions.cs file now in Visual Studio it will gray out the file as well because of the #if statement.

**Comment by akornich** [comment]
@mregni , did you forget to add Rollbar.NetCore.AspNet package to your project? We split the implementation into more packages starting from v3. Now Rollbar package only includes core functionality (just the notifier/logger) and RollbarTraceListener. All the integration for Asp.Net Core is within Rollbar.NetCore.AspNet package.

**Comment by akornich** [comment]
@mregni , actually, as you mentioned, the conditions compilation would cause the problem even if you added the the Rollbar.NetCore.AspNet package. Yes, I missed it when we moved to just netstandard2.0  build target. I'll try to make new release tomorrow. Thanks for catching it!

**Comment by mregni** [comment]
I updated the Rollbar.NetCore.AspNet package from 3.0.2 to 3.0.3 yes. 

Thanks! No hurry really, I just tot a downgrade to 3.0.2 again until you have time to fix it.

**Comment by mregni** [comment]
Sure no problem, thanks for the quick fix!

**Comment by akornich** [comment]
@mregni , v3.0.4 with the fix is out.

**Comment by mregni** [comment]
Thanks, working great!
