### ISSUE TITLE
Make the repo commitizen-friendly

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/Rollbar.NET#372]
Add https://github.com/commitizen/cz-cli to repo's dependencies.

Add config for commitizen to use https://www.npmjs.com/package/cz-conventional-changelog

This will provide the `git cz` command which makes creating conventional-changelog commits easy

This also needs we will need to adjust our contributing instructions for the community

**Comment by akornich** [comment]
we have been adding the agreed-upon commit message prefixes for awhile now. I guess we can close this one
