### ISSUE TITLE
Scrub fields don't appear to be scrubbed within request body's JSON data

### ISSUE THREAD

**Issue by beeradmoore** [rollbar/Rollbar.NET#375]
Sensitive data should be scrubbed before submission. According to the docs this is done with the ScrubFields list in the config. Checking where this is used, it should be scrubbed with the call to `ScrubPayload` in `RollbarClient`. I don't know if my test case isn't using this code flow or if there was some other setting I needed to change.  I can confirm that "password" is part of my scrub fields when this is called.

Test case: 
```
        public class FakeUserLogin
        {
            public string username { get; set; }
            public string password { get; set; }
        }

        [HttpPost]
        [Route("/test/scrub")]
        public ActionResult<string> TestScrub([FromBody] FakeUserLogin body)
        {
            /*
            foreach (var field in RollbarLocator.RollbarInstance.Config.ScrubFields)
            {
                Console.WriteLine(field);
            }
            */

            var rollbarPackage = new ExceptionPackage(new Exception("Testing scrubbing of data."));
            var packageDecorator = new HttpRequestPackageDecorator(rollbarPackage, HttpContext.Request, true);
            RollbarLocator.RollbarInstance.Log(ErrorLevel.Error, packageDecorator);

            return Ok("Done");
        }
```

Raw request that was sent:
```
POST /test/scrub HTTP/1.1
Content-Type: application/json; charset=utf-8
Host: localhost:5000
Connection: close
User-Agent: Paw/3.1.8 (Macintosh; OS X/10.14.4) GCDHTTPRequest
Content-Length: 53

{"username":"testusername","password":"testpassword"}
```

Raw json as logged on rollbar.
```
{
  "body": {
    "trace": {
      "frames": [], 
      "exception": {
        "message": "Testing scrubbing of data.", 
        "class": "System.Exception"
      }
    }
  }, 
  "uuid": "REMOVED", 
  "language": "c#", 
  "level": "error", 
  "timestamp": 1555119770, 
  "request": {
    "body": "{\"username\":\"testusername\",\"password\":\"testpassword\"}", 
    "url": "localhost:5000/test/scrub", 
    "headers": {
      "Content-Length": "53", 
      "Connection": "close", 
      "Content-Type": "application/json; charset=utf-8", 
      "Host": "localhost:5000", 
      "User-Agent": "Paw/3.1.8 (Macintosh; OS X/10.14.4) GCDHTTPRequest"
    }, 
    "params": null, 
    "query_string": "", 
    "method": "POST"
  }, 
  "custom": {}, 
  "environment": "local", 
  "platform": "Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64", 
  "framework": ".NETCoreApp,Version=v2.1", 
  "notifier": {
    "version": "3.0.4", 
    "name": "Rollbar.NET"
  }, 
  "metadata": {
    "customer_timestamp": 1555119770
  }
}
```

And as you can see "testpassword" still exists in the data submitted to rollbar. I can't build the project locally to debug what is going on with this.

Rollbar.NET 3.0.4 running in an ASP.NET core 2.1 project running on macOS 10.14.4.

**Comment by akornich** [comment]
@beeradmoore , i assume you did specify the fields to scrub in the config?

**Comment by beeradmoore** [comment]
I didn't specify, but I did confirm with that foreach loop that password was in `RollbarLocator.RollbarInstance.Config.ScrubFields`

**Comment by akornich** [comment]
@beeradmoore , thanks for reporting the issue. I'll be looking into it first thing tomorrow morning.

**Comment by akornich** [comment]
@beeradmoore , so far i see now issues with scrubbing (at least on Windows 10 and .NET Core 2.1). Here is an example with 
```
            newConfig.ScrubFields = new string[]
            {
                "log4net:UserName",
                "log4net:HostName",
                "log4net:Identity",
            };
```
[https://rollbar.com/Rollbar/Rollbar.Net/items/2548/occurrences/74617863604/](https://rollbar.com/Rollbar/Rollbar.Net/items/2548/occurrences/74617863604/)

**Comment by beeradmoore** [comment]
That Rollbar issue is not viewable to the public. And yep, I'll make a repro in the next few days and link it in here.

**Comment by akornich** [comment]
@beeradmoore , thanks! BTW, I did some testing of this issue within an Asp.Net Core WebApi app while logging things via direct calls to RollbarLogger from a controller's action and via RollbarMiddleware component. In both cases, scrubbing works as expected. So, still, there is no repro on my side...

**Comment by beeradmoore** [comment]
@akornich , I was able to reproduce it on 3.0.5, sample project [here](https://github.com/beeradmoore/RollbarScrubRepro). 

Add your access token here `var rollbarConfig = new RollbarConfig("......");`

Run this to replicate the issue.
```
curl \
  --request POST 'https://localhost:5001/api/test' \
  --insecure \
  --header 'Content-Length:53' \
  --header 'Connection:close' \
  --header 'Content-Type:application/json; charset=utf-8' \
  --header 'Host:localhost:5001' \
  --header 'User-Agent:Paw/3.1.8 (Macintosh; OS X/10.14.4) GCDHTTPRequest' \
  --data '{"username":"testusername","password":"testpassword3"}' 
```

This is what is logged in Rollbar as the raw json for the event.
```
{
  "body": {
    "trace": {
      "frames": [
        {
          "method": "RollbarScrubRepro.Controllers.TestController.Get(RollbarScrubRepro.Data.LoginData loginData)", 
          "lineno": 17, 
          "colno": 17, 
          "filename": "/somepath/git/RollbarScrubRepro/Controllers/TestController.cs"
        }
      ], 
      "exception": {
        "message": "Some error happened 2.", 
        "class": "System.Exception"
      }
    }
  }, 
  "uuid": "REMOVED", 
  "language": "c#", 
  "level": "error", 
  "timestamp": 1555563745, 
  "request": {
    "body": "{\"username\":\"testusername\",\"password\":\"testpassword3\"", 
    "url": "localhost:5001/api/test", 
    "headers": {
      "Content-Length": "53", 
      "Host": "localhost:5001", 
      "Accept": "*/*", 
      "User-Agent": "Paw/3.1.8 (Macintosh; OS X/10.14.4) GCDHTTPRequest", 
      "Connection": "close", 
      "Content-Type": "application/json; charset=utf-8"
    }, 
    "params": null, 
    "query_string": "", 
    "method": "POST"
  }, 
  "custom": {}, 
  "environment": "scrub_test", 
  "platform": "Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64", 
  "framework": ".NETCoreApp,Version=v2.1", 
  "notifier": {
    "version": "3.0.5", 
    "name": "Rollbar.NET"
  }, 
  "metadata": {
    "customer_timestamp": 1555563745
  }
}
```

**Comment by akornich** [comment]
@beeradmoore , thank you! I'll be looking into it shortly.

**Comment by akornich** [comment]
@beeradmoore , now I see why I had no luck reproducing this issue. Currently, scrubbing works based on payload JSON representation data elements. A value of an element will be scrubbed if the data element name is mentioned among the ScrubFields of the Rollbar config. In your use case, "password" is a part of the string-like content of `request.body` data element. Since a request body content could be anything we report is a "raw string" representation of its content without trying to interpret it in any way. So, scrubbing does work as intended.
To help your situation, we can try to add an attempt to interpret body value as a JSON and if it succeeds to add it as a JSON object. However, I am not sure how strict our API requirement for the body value to be a string is on the API server side. But we can give it a try...

**Comment by akornich** [comment]
@beeradmoore , the first test of the approach above looks much better:
```
"request": {
    "body": "{\"username\":\"User\",\"password\":\"***\"}", 
    "url": "localhost:20650/api/test", 
    "headers": {
      "Origin": "http://localhost:20650", 
      "Content-Length": "46", 
      "Accept-Language": "en-US,en;q=0.8,he;q=0.6,ru;q=0.4,uk;q=0.2", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "localhost:20650", 
      "Accept": "application/json", 
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763", 
      "Connection": "Keep-Alive", 
      "X-Original-Proto": "http", 
      "Cookie": "lang=en", 
      "Cache-Control": "no-cache", 
      "MS-ASPNETCORE-TOKEN": "57e19acb-c01e-4048-a0ec-37c1d5781241", 
      "Referer": "http://localhost:20650/swagger/index.html", 
      "X-Original-For": "127.0.0.1:53824", 
      "Content-Type": "application/json-patch+json"
    }, 
    "params": null, 
    "query_string": "", 
    "method": "POST"
  }, 
```

**Comment by akornich** [comment]
@beeradmoore , more testing went well. I'll be checking it in. as well as the change you suggested in PR #374 (but slightly modified version). i'll be making a new release containing these changes either today or tomorrow.

**Comment by beeradmoore** [comment]
> we can try to add an attempt to interpret body value as a JSON

Thats essentially what my workaround was, which is where it started killing me with the StreamReader closing issue as well. Glad to hear both are resolved.
