### ISSUE TITLE
Missing documentation on NLog plug-in (integration)

### ISSUE THREAD

**Issue by RudeySH** [rollbar/Rollbar.NET#399]
I can't get the NLog plug-in to work. I couldn't find any documentation on how to set it up, so that's why I'm here.

My NLog configuration looks like this:

    <nlog ...> 
        <extensions>
            <add assembly="Rollbar.PlugIns.NLog" />
        </extensions>
        <targets>
            <target xsi:type="Rollbar.PlugIns.NLog" name="Rollbar" />
        </targets>
        <rules>
            <logger name="*" minlevel="Error" writeTo="Rollbar" />
        </rules>
    </nlog>

I'm configuring Rollbar in `Application_Start` like this:

        var accessToken = WebConfigurationManager.AppSettings["myapp:RollbarAccessToken"];
        var environment = WebConfigurationManager.AppSettings["myapp:RollbarEnvironment"];
        RollbarLocator.RollbarInstance.Configure(new RollbarConfig(accessToken) { Environment = environment });

The app settings are in my `Web.config`.

When I turn on NLog's internal logging, I see the following stacktrace:

    Parsing configuration from D:\Path\To\MySolution\MyProject\web.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing D:\Path\To\MySolution\MyProject\web.config.  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Argument should not be NULL
    Parameter name: likeMe
      at Rollbar.Diagnostics.Assumption.AssertNotNull[T](T value, String parameterName)
      at Rollbar.Common.ReconfigurableBase.Reconfigure(Object likeMe, Type likeMeTypeOfInterest)
      at Rollbar.Common.ReconfigurableBase`2.Reconfigure(TBase likeMe)
      at Rollbar.RollbarConfig.Reconfigure(IRollbarConfig likeMe)
      at Rollbar.RollbarConfig.Rollbar.Common.IReconfigurable<Rollbar.IRollbarConfig,Rollbar.IRollbarConfig>.Reconfigure(IRollbarConfig likeMe)
      at Rollbar.RollbarLogger.Rollbar.IRollbar.Configure(IRollbarConfig settings)
      at Rollbar.PlugIns.PlugInCoreBase..ctor(IRollbarConfig rollbarConfig, Nullable`1 rollbarBlockingTimeout)
      at Rollbar.PlugIns.NLog.RollbarPlugInCore..ctor(IRollbarConfig rollbarConfig, Nullable`1 rollbarBlockingTimeout, RollbarTarget rollbarTarget)
      at Rollbar.PlugIns.NLog.RollbarTarget..ctor(IRollbarConfig rollbarConfig)
      at Rollbar.PlugIns.NLog.RollbarTarget..ctor()

What did I do wrong?

**Comment by akornich** [comment]
@RudeySH , please, refer to this sample we have available as Rollbar integration with NLog:
[https://github.com/rollbar/Rollbar.NET/blob/master/Samples/Sample.PlugIns.NLog.sln](https://github.com/rollbar/Rollbar.NET/blob/master/Samples/Sample.PlugIns.NLog.sln)

**Comment by RudeySH** [comment]
Alright, that one works. The main difference between this and my set-up is that I'm using .NET Framework (with App/Web.config), and the sample uses .NET Core (with appsettings.json).

I made a similar console app sample using .NET Framework 4.7.2, to demonstrate it does not work. Please take a look at [RudeySH/Rollbar.Sample.PlugIns.NLog.NetFramework](https://github.com/RudeySH/Rollbar.Sample.PlugIns.NLog.NetFramework).

I've put `throwExceptions="true"` in the NLog configuration. Running the sample will throw the aforementioned exception.

**Comment by akornich** [comment]
@RudeySH , conceptually both Core and Framework based integrations are the same. Rollbar NLog target has to be configured via an XML file. Rollbar itself can be configured either via XML:
[https://github.com/rollbar/Rollbar.NET/blob/master/Samples/Sample.Net.ConsoleApp/App.config#L7](https://github.com/rollbar/Rollbar.NET/blob/master/Samples/Sample.Net.ConsoleApp/App.config#L7)
using the dedicated configuration section
or 
via the json as in the sample that was mentioned in my first reply.

**Comment by RudeySH** [comment]
I didn't realize there's an XML configuration section available for Rollbar. I finally got the NLog plug-in to work now, thanks.

**Comment by kharpoh-entangled** [comment]
Is there anyway to make Rollbar nlog plugin to use the configuration (access token, environment) provided to RollbarLocator.RollbarInstance.Configure instead of using appsettings.json?

Thanks in advance!

**Comment by akornich** [comment]
Nope. The NLog plug-in uses its own dedicated RollbarLogger instance (not the shared one locatable via RollbarLocator). It loads its RollbarLogger configuration either via appsettings.json or via app.config.
