### ISSUE TITLE
Xamarin PCL support

### ISSUE THREAD

**Issue by keshavkaul** [rollbar/Rollbar.NET#4]
Hi, Would like to know if there are any plans to support Xamarin PCL. And what can i do to help in this regard?

**Comment by joanbarros** [comment]
Do you think it would be best to make this package compatible with Xamarin or create a wrapper that is compatible with Xamarin as a separate NuGet Package?

Thinking about this because in some instances you'd need specific API's for Xamarin. For instance when developing in Xamarin Forms you need to have some kind of interface that abstracts the implementation for each platform from the API. This code could live in the separate package as is specific to Xamarin...

**Comment by lanarchyste** [comment]
Hi,

I have created a Rollbar client for Xamarin based on the Rollbar.NET code

Although the library is operational, it has not been tested in production, so it is possible that there are some bugs

Link : https://github.com/lanarchyste/Xamarin.RollbarDotNet

**Comment by rokob** [comment]
I think this should probably end up being a separate package, however as part of the v1 updates we should have in mind how to make this easy to accomplish. I am going to add to the v1 milestone as a tracking task, not to mean that we will release a Xamarin package at the same time.

**Comment by akornich** [comment]
Looking at this info:
[https://blog.xamarin.com/net-standard-library-support-for-xamarin/](url)
Xamarin should be able to work with .NET Standard.
v1-alpha already targets .NETStandard2.0. I guess, it should "just work" :).

**Comment by akornich** [comment]
@keshavkaul : Rollbar.NET v1 supports netstandard 2.0 which is in turn supported (according to Microsoft) by:

Supported .NET implementations
The .NET Standard 2.0 is supported by the following .NET implementations:

.NET Core 2.0
.NET Framework 4.6.1
Mono 5.4
Xamarin.iOS 10.14
Xamarin.Mac 3.8
Xamarin.Android 8.0
Universal Windows Platform 10.0.16299

**Comment by buzzware** [comment]
@akornich That's great that you now support Xamarin, but it seems accidental. 

Your site doesn't mention Xamarin once https://www.google.com.au/search?q=site%3Arollbar.com+xamarin&oq=site%3Arollbar.com+xamarin&aqs=chrome.0.69i59j69i58.7863j0j4&sourceid=chrome&ie=UTF-8&tbs=li:1

It would give the fast growing Xamarin community (including myself) confidence to use Rollbar if your marketing and support specifically targeted it, and there are probably specific issues with Xamarin that you need to address to constitute full support for it eg. dealing with native iOS or Android exceptions as well as .Net ones.

**Comment by rivkahstandig3636** [comment]
@buzzware Supporting Xamarin is definitely not accidental, but I agree, we should do more to give Xamarin first-class support, and we will work on it!

**Comment by akornich** [comment]
A working Rollbar-with-Xamarin example is now checked in as part of v1.1.0.
[https://github.com/rollbar/Rollbar.NET/tree/master/Sample.Xamarin.Forms](url)
