### ISSUE TITLE
Authorization header not begin scrubbed

### ISSUE THREAD

**Issue by beeradmoore** [rollbar/Rollbar.NET#406]
When using `RollbarLocator.RollbarInstance.Log` to log an error the Authorization header is not scrubbed. Not sure if this is a bug or missing feature. According to the [Ruby docs](https://docs.rollbar.com/docs/gem-configuration-reference) there is a `scrub_headers` field. This doesn't exist in the [.NET docs](https://docs.rollbar.com/docs/dotnet).

**To Reproduce**
```
[HttpGet]
[Route("/test/error")]
public ActionResult<string> TestError()
{
    var exception = new Exception($"blah - {DateTime.Now}");
    var rollbarPackage = new ExceptionPackage(exception);
    var packageDecorator = new HttpRequestPackageDecorator(rollbarPackage, this.HttpContext.Request, true);
    RollbarLocator.RollbarInstance.Log(ErrorLevel.Error, packageDecorator);
    return Ok();
}
```

**Expected behavior**
Authorisation header is not sent to rollbar as that is a potential security risk. 

**Actual behaviour** 
```
curl --request GET 'localhost:5000/test/error' \
--header 'Connection:close' \
--header 'Content-Type:application/json; charset=utf-8' \
--header 'Host:localhost:5000' \
--header 'Authorization: Bearer SECRET_SAUCE'
```

SECRET_SAUCE is sent to rollbar. 

```
{
  "body": {
    "trace": {
      "frames": [], 
      "exception": {
        "message": "blah - 06/04/2019 06:13:50", 
        "class": "System.Exception"
      }
    }
  }, 
  "uuid": "f3314689ad6544e7b6f4061f58009b09", 
  "language": "c#", 
  "level": "error", 
  "timestamp": 1559592830, 
  "request": {
    "url": "localhost:5000/test/error", 
    "query_string": "", 
    "params": null, 
    "method": "GET", 
    "headers": {
      "Host": "localhost:5000", 
      "Accept": "*/*", 
      "User-Agent": "curl/7.54.0", 
      "Connection": "close", 
      "Content-Type": "application/json; charset=utf-8", 
      "Authorization": "Bearer SECRET_SAUCE"
    }
  }, 
  "custom": {}, 
  "environment": "local", 
  "platform": "Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64", 
  "framework": ".NETCoreApp,Version=v2.1", 
  "notifier": {
    "version": "3.2.0", 
    "name": "Rollbar.NET"
  }, 
  "metadata": {
    "customer_timestamp": 1559592830
  }
}
```

Currently using Rollbar.net 3.2.0 in an ASP.NET core app.

**Comment by akornich** [comment]
@beeradmoore, you need to set ScrubFields option of the RollbarConfig object used to configure the logger instance either programmatically or via an appconfig.xml or appsettings.json settings:
[https://docs.rollbar.com/docs/dotnet#section-rollbarconfig](https://docs.rollbar.com/docs/dotnet#section-rollbarconfig)
(the last two parameters in the linked section relate to scrubbing)

**Comment by beeradmoore** [comment]
@akornich Docs say scrub fields remove it from _POST and _SESSION (I assume that odd formatting is from a copy/paste job from php) not from headers. Ruby docs have authorization added to header ignore list by default. 

Adding it to scrub fields does remove it as expected.

Docs may need to be updated to include that scrub fields will remove it from headers as well. And maybe add Authorization and authorization by default?

**Comment by akornich** [comment]
@beeradmoore, in Rollbar.NET, the ScrubFields applied across the whole payload data regardless of what container of a field (if any).

**Comment by akornich** [comment]
@beeradmoore, I'll bring up your suggestion for adding Authorization into defaults for scrubbing.

**Comment by beeradmoore** [comment]
Cheers :) 

When it wasn't scrubbing it by default (like how Ruby docs says it does for that platform) I thought it may have been an issue similar to #375 when it wasn't scrubbing. Although I totally get how with rollbar being on so many platforms that I shouldn't expect it to have feature/config parity across all platforms.

**Comment by akornich** [comment]
@beeradmoore, correct, most of the SDKs were developed independently by different people and at different timeframes with the first priority being to address most critical features and error reporting capabilities of each platform. That said, we are already starting an effort on unifying feature sets and config properties across the SDKs.

**Comment by akornich** [comment]
#407

**Comment by beeradmoore** [comment]
That makes sense that they would differ because of that. We use Mixpanel and it is similar across platforms. 

Thanks for helping with the original issue.
