### ISSUE TITLE
Can not able to configuration and register the Rollbar logger with the application services

### ISSUE THREAD

**Issue by ParthiKarnan** [rollbar/Rollbar.NET#409]
`
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Rollbar;
using System;

namespace RollbarCore.API
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {      

            ConfigureRollbarSingleton();

            services.AddRollbarLogger(loggerOptions =>
            {
                loggerOptions.Filter = (loggerName, loglevel) => loglevel >= LogLevel.Trace;
            });

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseRollbarMiddleware();

            app.UseHttpsRedirection();
            app.UseMvc();
        }

        /// <summary>
        /// Configures the Rollbar singleton-like notifier.
        /// </summary>
        private void ConfigureRollbarSingleton()
        {
            string rollbarAccessToken = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx";

            string rollbarEnvironment = "AspNetCoreMiddlewareTest";

            RollbarLocator.RollbarInstance
              // minimally required Rollbar configuration:
              .Configure(new RollbarConfig(rollbarAccessToken) { Environment = rollbarEnvironment })
              // optional step if you would like to monitor Rollbar internal events within your application:
              .InternalEvent += OnRollbarInternalEvent;
        }

        /// <summary>
        /// Called when rollbar internal event is detected.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="e">The <see cref="RollbarEventArgs"/> instance containing the event data.</param>
        private static void OnRollbarInternalEvent(object sender, RollbarEventArgs e)
        {
            Console.WriteLine(e.TraceAsString());            
        }
    }
}`

I have added Rollbar configuration and register the Rollbar logger with the application services with above code **Rollbar 3.2.0** version followed by https://docs.rollbar.com/docs/dotnet document into my project using asp net.core 2.2 web api. During the configuration I'm getting the following errors.

1>Startup.cs(31,22,31,38): error CS1061: 'IServiceCollection' does not contain a definition for 'AddRollbarLogger' and no accessible extension method 'AddRollbarLogger' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)
1>Startup.cs(52,17,52,37): error CS1061: 'IApplicationBuilder' does not contain a definition for 'UseRollbarMiddleware' and no accessible extension method 'UseRollbarMiddleware' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)

@brianr @kshep @waltjones @jondeandres @ruZZil 

Can anyone please help me to come out of it?

Thanks,
Parthi

**Comment by siva93** [comment]
Hi Parthy,

Please use the  "Rollbar.NetCore.AspNet" package and also add the  inject the             

> services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

in startup.cs file

Happy coding :)

**Comment by akornich** [comment]
The missing types are defined within the Rollbar.NetCore.AspNet Nuget package.
@ParthiKarnan , please, use the following sample application as a reference on how to integrate Rollbar Notifier within an Asp.Net Core application: [https://github.com/rollbar/Rollbar.NET/blob/master/Samples/Sample.AspNetCore2.WebApi.sln](https://github.com/rollbar/Rollbar.NET/blob/master/Samples/Sample.AspNetCore2.WebApi.sln)

**Comment by akornich** [comment]
@ParthiKarnan, can we close the issue or you are still running into some obstacles?

**Comment by ParthiKarnan** [comment]
Hi @siva93 and @akornich ,
After install the Rollbar.NetCore.AspNet package, it's working fine for me. Thanks for you guys support. 
@akornich Please close the ticket.

**Comment by akornich** [comment]
@ParthiKarnan , thanks for the update. I am glad you are unblocked.
