### ISSUE TITLE
Include stack trace in manually logged caught exceptions.

### ISSUE THREAD

**Issue by AFDevMike** [rollbar/Rollbar.NET#410]
**Is your feature request related to a problem? Please describe.**
I would like to see a traceback with stack trace when I log caught exceptions to be able to find the locaiton of the error even though it was handled / caught.

**Describe the solution you'd like**

```
try {
    // Do IO that throws
} catch (Exception ex) {
    // Handle Ex
    RollbarLocator.RollbarInstance.Logger.Error(ex); 
}
```

Include stack trace and see in Traceback Tab of `rollbar.com`

It appears this is available and configurable for rollbar-gem according to this git-issue:
https://github.com/rollbar/rollbar-gem/issues/243

Do not see any similar config in `RollbarConfig` for .NET here: https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar/RollbarConfig.cs

**Additional context**
This is what I see presently for the above code example:
![2019-06-14 11_53_37-#110 System Exception_ Mikes testing A CAUGHT Rollbar Server Error - AFCloud - R](https://user-images.githubusercontent.com/38863910/59531549-1aaaff80-8e9b-11e9-928b-d095a0cdaed2.png)

**Comment by akornich** [comment]
@AFDevMike, reporting an exception via a Rollbar logger does include exception's call trace stack and Data property value whenever they are available. We do not have any switch to turn it on/off. We forward all the available attributes of an exception as long as they are available. 
I am not sure I fully understand your question. Would you be able to post here the complete raw (JSON) representation of the exception occurrence you are referring to in your post? Just make sure to musk out any confidential info. Thank you!

**Comment by AFDevMike** [comment]
Sure:

```
{
  "body": {
    "message": {
      "body": "This is the error logs message"
    }
  }, 
  "uuid": "IF YOU NEED THIS LET ME KNOW", 
  "language": "c#", 
  "level": "error", 
  "timestamp": 1560535610, 
  "title": "This is the error logs message", 
  "request": {
    "httpRequestTimestamp": "2019-06-14T11:06:47.6344331-07:00", 
    "protocol": "HTTP/1.1", 
    "headers": {
      "Origin": "http://localhost:5000", 
      "Content-Length": "367", 
      "Accept-Language": "en-US,en;q=0.9", 
      "Accept-Encoding": "gzip, deflate, br", 
      "Host": "localhost:5000", 
      "Accept": "application/json, text/plain, */*", 
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36", 
      "Connection": "keep-alive", 
      "Content-Type": "application/json"
    }, 
    "url": "localhost:5000/api/Account/Login", 
    "httpRequestID": "0HLNGUC8JK5B9:00000001", 
    "params": null, 
    "query_string": "", 
    "scheme": "http", 
    "method": "POST", 
    "statusCode": 200
  }, 
  "custom": {
    "LogEventID": "0"
  }, 
  "environment": "Development", 
  "platform": "Microsoft Windows 10.0.17763 ", 
  "framework": ".NETCoreApp,Version=v2.2", 
  "notifier": {
    "version": "3.2.0", 
    "name": "Rollbar.NET"
  }, 
  "metadata": {
    "customer_timestamp": 1560535608
  }
}
```

**Comment by AFDevMike** [comment]
I apologize.  I was `New`ing up and exception and logging it without throwing it to test as my "describe the solution I would like" indicated.  

Thus no stack trace.

**Comment by akornich** [comment]
OK, that makes sense. That would be my next question :).
So, is there anything else I can help you with?

**Comment by AFDevMike** [comment]
No, thank you!

**Comment by akornich** [comment]
Resolved.
