### ISSUE TITLE
Rollbar.Net.AspNet: add auto-capture of the current HTTP request/response to RollbarHttpModule

### ISSUE THREAD

**Issue by akornich** [rollbar/Rollbar.NET#418]

**Comment by Lobosque** [comment]
@akornich I see that you recently merge a PR do add response capture to NetCore - are there plans to also capture request parameters?

**Comment by akornich** [comment]
@Lobosque , we can probably add it as well. would you like to open a request for it?

**Comment by Lobosque** [comment]
@akornich do you mean as formalizing a feature request or as in "pull request"?
I believe this to be way more important than logging the response, as it is usually more helpful in a debugging situation to know what went into the system than what went out.
@akornich this, together with the fact that there are no "local vars" for .NET in Rollbar, makes it very difficult to debug problems.
I know that it is actually possible to log the request if you set it up, but having that out of the box would be very helpful.

**Comment by akornich** [comment]
@Lobosque ,  our .Net Core plugin's RollbarMiddleware was capturing the current HTTP request since its first release, for example:
[https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar.NetCore.AspNet/RollbarMiddleware.cs#L157](https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar.NetCore.AspNet/RollbarMiddleware.cs#L157)
[https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar.NetCore.AspNet/RollbarLogger.cs#L118](https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar.NetCore.AspNet/RollbarLogger.cs#L118)
[https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar.NetCore.AspNet/RollbarHttpContextPackageDecorator.cs#L48](https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar.NetCore.AspNet/RollbarHttpContextPackageDecorator.cs#L48)
The same goes for other web framework plug-ins. 
The HTTP requests were already captured, so we are now adding a capture of the responses.
While writing my first reply to your initial post, I thought you implied that you would like to see some extra request parameters captured and I was asking you to create a feature request with the list of the parameters you would like to be added. We are always ready to add improvements to the SDK based on our customers' requests.
Yes, we still could not find a way to capture local vars in .NET, but we do have a helper class that could be very handy in helping to capture your application object states as needed: [https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar/RollbarAssistant.cs#L10](https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar/RollbarAssistant.cs#L10)

Best regards,
- Andrey
