### ISSUE TITLE
Enable Persistence to Maintain Logs while Offline

### ISSUE THREAD

**Issue by noahcolvin** [rollbar/Rollbar.NET#424]
**Is your feature request related to a problem? Please describe.**
I am in the progress of adding Rollbar to an application that runs on UWP and Xamarin iOS and one of the scenarios I need to cover is reporting application crashes. To do this I am registering handlers on `AppDomain.CurrentDomain.UnhandledException` and `TaskScheduler.UnobservedTaskException` as per the examples in the Rollbar documentation.

This works great normally, but a good deal of our customer base is mobile and a connection is not guaranteed. If the application were to crash while they do not have a connection, the stack and all related information are lost.

This is functionality that `HockeyApp` has been providing but as that service is going away we are looking at alternatives. Rollbar is used pretty heavily in our organization's applications so it would make sense to explore how it would work here too. At the moment this is a blocker for us.

**Describe the solution you'd like**
If the library is unable to send a log, such as due to a network error, persist the log so that it may be sent when the device is back online. This should be able to survive the application closing, crashing or a device reboot.

Ideally it would monitor connectivity and send unsent messages when online and the app is running.

**Describe alternatives you've considered**
We have discussed writing out the errors to a file on the unhandled exception events ourselves and then at next startup, send those through Rollbar. This is essentially what `HockeyApp` does today, but we feel like we'd potentially lose some of the context around the error using this method. We also had planned on using Rollbar for more than just application crashes and this quickly becomes tedious if we have to do something similar for all log types and forces us to manage what Rollbar has and has not sent.

Other alternatives would be to migrate to `HockeyApp`'s successor, `App Center`, or investigate other products.

**Additional context**
We found #413 while searching for a solution. I don't know if that person has further reached out to create a request (I didn't see one here) but I thought I'd add my two cents that there is another person/team who could make use of this feature.

Thank you.

**Comment by akornich** [comment]
Hi @noahcolvin , thank you very much for the detailed request. We were considering adding payload persistence for some time now. I guess this could be an opportunity to start working on one once we get a green light for it. I'll post here another update once I have some time estimates for this work.

**Comment by noahcolvin** [comment]
Thanks for your quick reply. I'll let the team know and look forward to hearing about any progress.

**Comment by akornich** [comment]
@noahcolvin , I got a green light for adding the persistence to the SDK. In terms of feature completion readiness, I am not ready to provide a precise answer yet (I need to complete one higher priority item before I can start on this feature). But having it released some time around the end of August or early September is probably a reasonable expectation.

**Comment by noahcolvin** [comment]
@akornich that's awesome! I really appreciate the fast turnaround in prioritization and communication. If you need any additional information from me please do not hesitate to ask. Thanks!

**Comment by akornich** [comment]
@noahcolvin , you are welcome! I you, guys, have any specific requirements to this feature, please, let me know asap. For example, how would you see it fit with other currently existing features (like rate limiting or retries limit)? Also, would you like it to be an optional feature that can be turned on/off as needed or would you prefer it to kick in automatically as soon as network disconnection detected otherwise use in-memory queueing (like it is right now), etc?

**Comment by noahcolvin** [comment]
I'm fairly new to using Rollbar so I'm not sure I know what other features would make sense to integrate here. I could further explain our problem if that would help.

Our client base spends their time in a mix of being in the office and on location with their clients. So while they should have a reliable connection in the office, where they go throughout the day could be to rural areas where, even if they have an LTE enabled device, connectivity may be spotty or non-existent. Because of this, we generally expect our users to load the data they need from the office and then take it with them to use throughout the day. Since they are spending a large amount of time in the field, if an exception or crash were to occur we still want to be alerted asap in case we need to reach out.

So in our case, I don't think we'd ever have a reason to disable this feature; however, I could see other users wanting the ability to disable it.

I would expect that the existing configuration would apply when coming back online. That may be as simple as having a queue of logs to send and, when there is connectivity, sending those using the corresponding asynchronous `ILogger` methods (though I suspect it'd be more complicated behind the scenes). If any of those would fail due to the network or if you can detect this condition reliably, they should stop attempting to send and remain queued until connectivity is restored.

**Comment by akornich** [comment]
@noahcolvin , thanks for the details!
yes, for now, we are leaning towards the solution where the payload persistence is essentially activated automatically when network disconnection is detected. This way the hosting app does not have to do anything to enable/disable the persistence, while there is no performance impact of file operations happening constantly when it is not really needed.
