### ISSUE TITLE
NullReferenceException in CompleteProcessing

### ISSUE THREAD

**Issue by mniederw** [rollbar/Rollbar.NET#436]
In V3.5 calling RollbarQueueController.Instance.Stop(true);
will lead to call RollbarQueueController.CompleteProcessing() twice and 
so the following code will throw a NullReferenceException:

RollbarQueueController.CompleteProcessing(){ ...
this._cancellationTokenSource.Dispose(); // here it throws a NullReferenceException on second call
this._cancellationTokenSource = null;
... }

A change of the line to the following code did solve the problem:

this._cancellationTokenSource?.Dispose();

**Comment by akornich** [comment]
@mniederw , thanks for catching it! the fix (and more) will be coming out soon (probably by the end of this week)...
