### ISSUE TITLE
StoreContext.sqliteConnectionString is hardcoded

### ISSUE THREAD

**Issue by Janek91** [rollbar/Rollbar.NET#465]
**Describe the bug**
Hardcoding sqliteConnectionString and setting it to localAppData directory only on non-windows machines causes IO exception when app is trying to create DB in directory in which has no write permissions.

**To Reproduce**
1. Install you sample application which has Rollbar implemented under Program Files directory on Windows
2. Try execute application
3. Your app crashes because it has no permission to create RollbarPayloadsStore.db file there

**Expected behavior**
There should be a way for developers to pass directory for RollbarPayloadsStore.db during Rollbar singleton configuration.

**Rollbar Client - Rollbar.NET Hosting Environment (please complete the following information):**
 - Rollbar.NET Host type: _desktop app_
 - OS and its version: _Windows_
 - .NET flavor and its version: .NET Standard 2.0
 - Application framework and its version: WPF
 - Rollbar.NET Version: 3.6.0-beta

**Comment by akornich** [comment]
@Janek91 , thanks for reporting the issue! Completely agree - it does make sense to provide a way for the users to specify a custom connection string. I will be adding it soon.
