### ISSUE TITLE
Sample.AspNetCore2.WebApi does not work with nugets?

### ISSUE THREAD

**Issue by Lechus** [rollbar/Rollbar.NET#468]
**Describe the bug**
Downloaded repo.
Opened Sample.AspNetCore2.WebApi sln in VS2017.
Provided own access_token
Ran project
Got 3 exceptions sent to Rollbard. - Correct.

Unloaded Rollbar projects.
Added nugets (v3.5)
Clean/Rebuild success.
Run - no exception sent to Rollbar ?

**Expected behavior**
Get 3 exceptions in Rollbar using nugets.

Net Framework 4.8, Core 2.1.13, Windows 10 x64  1903

Got CommunicationErrorEventArgs exception:
//TODO: handle/report basic communication error while attempting to reach Rollbar API service... 

The given key 'body' was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Rollbar.DTOs.Request.get_PostBody()
   at Rollbar.RollbarClient.ScrubHttpMessages(PayloadBundle payloadBundle)
   at Rollbar.RollbarClient.EnsureHttpContentToSend(PayloadBundle payloadBundle)
   at Rollbar.RollbarClient.PostAsJsonAsync(PayloadBundle payloadBundle)

Payload:
`{
    "access_token": "removed",
    "data": {
        "environment": "RollbarNetSamples",
        "body": {
            "telemetry": [{
                    "timestamp_ms": 1572438112405,
                    "source": "server",
                    "level": "info",
                    "type": "network",
                    "body": {
                        "method": "GET",
                        "url": "localhost:54043/api/values",
                        "status_code": "200",
                        "start_timestamp_ms": 1572438112401
                    }
                }
            ],
            "message": {
                "body": "ValuesController.Get() is called...637080349152542843"
            }
        },
        "level": "critical",
        "timestamp": 1572438115,
        "platform": "Microsoft Windows 10.0.18362 ",
        "language": "c#",
        "framework": ".NETCoreApp,Version=v2.1",
        "request": {
            "httpRequestTimestamp": "2019-10-30T12:21:52.3271267+00:00",
            "httpRequestID": "0HLQT6EVDC20G:00000001",
            "scheme": "http",
            "protocol": "HTTP/1.1",
            "statusCode": 200,
            "url": "localhost:54043/api/values",
            "query_string": "",
            "params": null,
            "method": "GET",
            "headers": {
                "Cache-Control": "no-cache",
                "Connection": "Keep-Alive",
                "Pragma": "no-cache",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
                "Accept-Encoding": "gzip, deflate, br",
                "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
                "Host": "localhost:54043",
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36",
                "Upgrade-Insecure-Requests": "1",
                "Sec-Fetch-User": "?1",
                "Sec-Fetch-Site": "none",
                "Sec-Fetch-Mode": "navigate",
                "MS-ASPNETCORE-TOKEN": "fc813b55-c18b-4fd5-8787-d2925741b614",
                "X-Original-Proto": "http",
                "X-Original-For": "127.0.0.1:57186"
            }
        },
        "response": {
            "status_code": 200
        },
        "custom": {
            "LogEventID": "0"
        },
        "title": "ValuesController.Get() is called...637080349152542843",
        "uuid": "fe348a1a4ee64116a3ac7994064de7c2",
        "notifier": {
            "name": "Rollbar.NET",
            "version": "3.5.0",
            "configured_options": {
                "AccessToken": "removed",
                "EndPoint": "https://api.rollbar.com/api/1/",
                "ScrubFields": [],
                "ScrubWhitelistFields": [],
                "LogLevel": "debug",
                "Enabled": true,
                "Transmit": true,
                "RethrowExceptionsAfterReporting": false,
                "Environment": "RollbarNetSamples",
                "Server": null,
                "Person": null,
                "ProxyAddress": null,
                "ProxyUsername": null,
                "ProxyPassword": null,
                "MaxReportsPerMinute": null,
                "ReportingQueueDepth": 20,
                "MaxItems": 0,
                "CaptureUncaughtExceptions": true,
                "PersonDataCollectionPolicies": "None",
                "IpAddressCollectionPolicy": "Collect"
            }
        }
    }
}`

**Comment by Lechus** [comment]
OK.
Looks like it is fixed in 3.6.0-beta.

**Comment by akornich** [comment]
@Lechus , thanks for reporting the issue! If it looks fixed in 3.6.0-beta, I'll be closing this issue as already resolved. 3.6.0-beta seems to be doing well. We have 237 downloads of it (from NuGet) and 0 major issues reported against it so far. I guess we can promote it from "beta" sometime next week.
