### ISSUE TITLE
Update Microsoft.AspNetCore.Http 

### ISSUE THREAD

**Issue by ScarlettCode** [rollbar/Rollbar.NET#471]
**Describe the bug**
Due to [this](https://github.com/aspnet/AspNetCore/issues/16875) issue with a package conflict can we look at updating the "Microsoft.AspNetCore.Http" package within this repo?

**Rollbar Client - Rollbar.NET Hosting Environment (please complete the following information):**
 - Rollbar.NET Host type: mobile app
 - OS and its version: Android
 - .NET flavor and its version: .NET Standard
 - Application framework and its version: Xamarin
 - Rollbar.NET Version: 3.5.0
 - Applicable Rollbar Plug-in (if any):
 - Applicable custom third party logging library/framework integration (if any):
 - Applicable Browser (if any):

**Comment by akornich** [comment]
#472
