### ISSUE TITLE
Address access token in the header vs in the payload

### ISSUE THREAD

**Issue by akornich** [rollbar/Rollbar.NET#48]

**Comment by akornich** [comment]
I need some help here: is there a spec on how the access token needs to be reported within the header...

**Comment by coryvirok** [comment]
Heh, this is definitely missing from our docs, but here's how we do it in Node: https://github.com/rollbar/rollbar.js/blob/master/src/server/transport.js#L100

It's just an extra HTTP header that gets sent with each request.

**Comment by akornich** [comment]
Cory, thank you! Done.
