### ISSUE TITLE
RollbarPayloadsStore.db ?

### ISSUE THREAD

**Issue by milovidov983** [rollbar/Rollbar.NET#482]
After updating to version 3.6.3, the library began to create the `RollbarPayloadsStore.db` file, why is this necessary and how to disable it? I don’t need extra files in the project and I didn’t really like the appeared sqlite dependency

**Comment by akornich** [comment]
Hi @milovidov983, 
here is the reason:
starting past v3.5.0 release, the SDK natively supports the persistence of the payloads in case of intermittent Internet connectivity. The RollbarPayloadStore.db file is used to store the payloads in case of the disconnection. The preserved payloads are resent once connectivity is back on.
The RollbarConfig allows specifying a custom name and a custom location of the db.  
This payload persistence feature is not optional and can not be disabled. Internally, it only kicks in when a disconnection is detected. When connectivity is on and stable, the persistence is omitted and the payloads sent outright from an in-memory queue.

**Comment by RudeySH** [comment]
Do we need to deploy this file to production, or will Rollbar create it runtime if it's not already created?

Also, should we commit this file to source control?

**Comment by akornich** [comment]
@RudeySH , the file will be created if it is not there. Hence, no need to deploy or place it under source control.
