### ISSUE TITLE
Explore possibility of being able to use RollbarLogger and RollbarLoggerProvider outside AspNetCore middleware

### ISSUE THREAD

**Issue by mario-mestrovic** [rollbar/Rollbar.NET#497]
Hi. I've been using Rollbar with log4net before (as a custom appender implementation) and would like to have similar experience with built in .net core logging system.
Currently if I want to have logging in AspNetCore app I need to register the middleware. It would be nice if RollbarLoggerProvider wasn't an internal class so I can use it without the exception handler middleware and request logging.

Also what would be great is to slice the aspnet core package into 2 packages. One for general .net (no dependency for http stuff such as IHttpContextAccessor) and the other with all the middleware you now have for plug and play usage.

Exposing the logger and provider as public would make them extendable.
Not having a direct dependency on IHttpContextAccessor just for package decoration would be great for flexibility. Ex. Instead of directly injecting IHttpContextAccessor to the provider you can inject your own context abstraction which can be used by the logger to decorate packages. Overriding that would then mean you can implement your own to have control of the package.

Btw, great work :)

**Comment by akornich** [comment]
@mario-mestrovic , thanks for the good suggestions!
We can make `RollbarLoggerProvider` public ( and probably should have made it public in the first place :)  ).
The RollbarLogger implementing Asp.NetCore's ILogger is already public.

I am not sure I fully understand what you mean by:
"Also what would be great is to slice the aspnet core package into 2 packages. One for general .net (no dependency for http stuff such as IHttpContextAccessor) and the other with all the middleware you now have for plug and play usage."
We already have Rollbar Nuget package that implements core Rollbar functionality for any .NET based application and is used internally by our Asp.NetCore plugin that simplifies Rollbar integration with Asp.NetCore apps. That Rollbar core package works with all other .NET 'flavors": .NET, .NET Core, Mono, Xamarin, etc..
