### ISSUE TITLE
Rollbar.NET attempts to write to application container's base directory in Release-type builds on an iOS device

### ISSUE THREAD

**Issue by duraz0rz** [rollbar/Rollbar.NET#498]
**Describe the bug**
This is similar to #485, but happens when an application with Rollbar.Net is deployed to an iOS device in a Release-like build.

We have a smoke test build that allows us to build a release-like artifact and deploy to our development iPads. We've noticed that the app builds and deploys to the device successfully, but the app immediately crashes when Rollbar attempts to write its database file to disc.

In inspecting the Console logs, Rollbar.Net is trying to write into the app container's directory, which the kernel denies. Rollbar.Net tries again in that same directory, and then crashes with the error in #485. Setting `LocalPayloadStoreLocationPath` does not affect where Rollbar.Net attempts to store the database; it is effectively ignored.

Note that `3.6.0-beta` had the correct behavior (store the database under the Documents folder), but seems to be broken in `3.6.2`, which is the version we were trying to upgrade to. We can't upgrade to `3.7.1` right now as we are using an older version of SQLite.Net and the underlying SQLitePCLRaw version conflicts with EF Core.

**To Reproduce**
1. Set `LocalPayloadStoreLocationPath` to some directory under the application container (like Documents).
2. Build and deploy the app to an iOS device under a Release build.
3. Start the app.

**Expected behavior**
I would expect the app to not crash and the database to be stored in the location specified by `LocalPayloadStoreLocationPath`.

**Rollbar Client - Rollbar.NET Hosting Environment (please complete the following information):**
 - Rollbar.NET Host type: Mobile app
 - OS and its version: iOS 13
 - .NET flavor and its version: Mono
 - Application framework and its version: Xamarin.iOS 13.10.0.17
 - Rollbar.NET Version: 3.6.2

**Comment by akornich** [comment]
@duraz0rz, thanks for reporting the issue. BTW, for now, as a work-around, you can disable payload persistence to avoid the crash. I'll try to have a fix published sometime this week.

**Comment by duraz0rz** [comment]
That's what we did...Thank you!
