### ISSUE TITLE
Explore possibility of integration with WorkerService (.Net Core 3.1)

### ISSUE THREAD

**Issue by Lechus** [rollbar/Rollbar.NET#499]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there is no package for a simple working injections of Rollbar.

**Describe the solution you'd like**
Be able to do simple:
services.AddRollbarLogger();

**Describe alternatives you've considered**
Rollbar.NetCore.AspNet - is dependant on HttpContext (Net Core is throwing errors on start-up), class is internal, etc.

**Additional context**
Microservices using WorkerService template (VS2019) need easy way to inject Rollbar to send Errors.

https://github.com/rollbar/Rollbar.NET/issues/497

**Comment by akornich** [comment]
#511
