### ISSUE TITLE
Older .NET Version Support

### ISSUE THREAD

**Issue by Crisfole** [rollbar/Rollbar.NET#5]
There are some good tools that are stuck on older versions of .NET

Would be good to offer at least NET30 support.

**Comment by focusdada** [comment]
Some suggestion with @Crisfole

**Comment by rokob** [comment]
We are going to add support for as many .net versions as possible and document it as part of the new v1 release. If we decide not to support some versions that will be clearly explained.

**Comment by akornich** [comment]
Supporting Full .NET versions below v4.0 most likely will require some code changes involving conditional compilation tags. The same goes for supporting .NET Core and .NET Standard below v2.0.

**Comment by akornich** [comment]
closing this one since we already have a superset issue addressed by:
[https://github.com/rollbar/Rollbar.NET/issues/34](url)
