### ISSUE TITLE
System.PlatformNotSupportedException on Xamarin.Forms Android

### ISSUE THREAD

**Issue by rezamohamed** [rollbar/Rollbar.NET#505]
I am simply trying to get started on Xamarin forms, I installed the current Rollbar package 3.8 to my forms and Android projects, 

**To Reproduce**
Added RollbarHelper to the root of the xamarin forms app 4.5.0.396,  And added the simplest config to Rollbarhelper RollbarLocator.RollbarInstance.Configure(new RollbarConfig(Constants.RollbarAccessToken));
Added the Config to MainActivity in the Android project.             RollbarHelper.ConfigureRollbarSingleton();

**Expected behavior**
To simply start the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/18199852/76999189-407e9c80-6924-11ea-9a39-a5a008d19b1d.png)

![image](https://user-images.githubusercontent.com/18199852/77008108-8a22b380-6933-11ea-95ca-9cd943214d59.png)

**Comment by rezamohamed** [comment]
I think I found the issue - in Debug/Windows/Exception Settings - I had checked ALL in 'Common Language Runtime Exceptions'. Resetting that back to the Default items only lets me proceed. I am unsure if this is by design or is a bug.

![image](https://user-images.githubusercontent.com/18199852/77021601-2d37f500-6955-11ea-8a91-e8de3b19d2d7.png)

**Comment by akornich** [comment]
hi @rezamohamed, the exception is expected in this scenario and we gracefully handle it. However, whenever you have the "Break When Thrown" feature of the Visual Studio enabled for a particular exception type the debugger will break at its origin regardless of how the exception was handled. 
Some of the .NET API may not be available in cross-platform applications we expect that and handle it properly when it happens. It is by design and works as intended.
You did the right thing by disabling the "Break When Thrown" for that exception type. Just let it run and enjoy the benefits of using Rollbar.
You can also use [this example](https://github.com/rollbar/Rollbar.NET/blob/master/Samples/Sample.Xamarin.Forms.sln) as a reference implementation of Rollbar.NET integration into a Xamarin app.
Good luck and do not hesitate to ask for any help with the SDK here!

**Comment by rezamohamed** [comment]
I have the global unhandled exception method right from your demo in my application for XF Android, and then executed a faulty piece of code. I get a System.Reflection.TargetInvocationException on my screen, I have hit continue on the Debugger a couple of times. Am I supposed to see a notification of this in the Rollbar dashboard? I don't see anything.

![image](https://user-images.githubusercontent.com/18199852/77124388-b95b2280-6a10-11ea-8df4-3c67573d5334.png)

**Comment by akornich** [comment]
@rezamohamed , can you post here the call stack of the exception? (btw, you do have "Break When Thrown" enabled for this exception type - in general, let it propagate throw the call stack and if it was handled at some point - it could represent a legit but recoverable error).

**Comment by rezamohamed** [comment]
When the Exception occurred, I tried to 'Attach to process' the adb.exe (the error is when running the Android emulator) and VS19 get hung up every time hence unable to get the call stack. The repro is very easy, I just created a new XF app, and then and then in the MainPage.xaml referenced a TextColor of something that didn't exist TextColor="{StaticResource doesntexist}"

That being said, yes, I do have that Exception in the 'Break when thrown' checked. I guess I am misunderstanding about how Rollbar should work. My expectation was that since I hit an unhandled exception, it would break, and also send an exception message to Rollbar. If this was a live app, since there is no debugging, would Rollbar just get the exception and the app crash?

**Comment by akornich** [comment]
@rezamohamed , the SDK would forward caught exceptions to the project's Rollbar Dashboard, assuming its logger was invoked to do so. There are multiple ways of doing so, for example, invoke a Rollbar logger from a catch block of try-catch statement and report the caught exception. If the application framework provides a sort of global application/process or thread or app domain-wide exception handler  - implement the handler and invoke a Rollbar logger from within the handler to forward a reported exception to the Rollbar Dashboard.

**Comment by akornich** [comment]
@rezamohamed , can we close this one as well?

**Comment by rezamohamed** [comment]
yes, please
