### ISSUE TITLE
Creating a Rollbar service in a shared CS proj in Xamarin.Forms

### ISSUE THREAD

**Issue by rezamohamed** [rollbar/Rollbar.NET#506]
I am using Rollbar with a Xamarin Forms App with Prism. I have a Shared CS project, in addition to the XF, Android, and iOS proj, that has all the plumbing code like Services, Models, ApiService etc. I would like to make a Rollbar service in the Shared App that can be used across my XF App. I can register this service using Prisms Service Locator, but I am unclear on how this would affect RollbarLocator. 

Currently, I have simply just added Rollbar to all projects including the Shared CS project, I am noticing a RollbarPayloadsStore.db in the Shared Project along with one in the XF project. Do I need to delete one? Can you provide some guidance on how to make Rollbar a Service from my shared project that I can inject either via the Constructor in my ViewModel or creating an instance?

![image](https://user-images.githubusercontent.com/18199852/77108139-b3a11500-69ef-11ea-96c3-e838fbe31dd8.png)

**Comment by akornich** [comment]
hi @rezamohamed , the `RollbarLocator` provides you with access to the shared/singleton instance (consider it an application/process-wide global service component) of the `RollbarLogger` implementing `IRollbar` interface. The `RollbarFactory` can be used to create similar `RollbarLogger` instances as needed. See following for more details:
https://docs.rollbar.com/docs/more-advanced-logger-usages#section-logging-using-the-singleton-like-instance-of-the-logger-via-the-rollbar-locator
https://docs.rollbar.com/docs/more-advanced-logger-usages#section-logging-using-a-scoped-instance-of-the-logger
All the `RollbarLogger` instances implementing `IRollbar` can be configured independently using corresponding instances of RollbarConfig.
The .db file is a Sqlite database file that is used as a local payload store whenever local payload persistence is enabled. Even that it is added to multiple projects using the Rollbar SDK you get one instance of it at runtime located either in the application folder or user folder or a custom configured location (depending on the runtime platform and/or custom RollbarConfig settings, if any).

**Comment by rezamohamed** [comment]
so if I am understanding this correctly, leaving the current implementation as is with the multiple SqlLite DB's is ok?

**Comment by akornich** [comment]
yes, correct...

**Comment by akornich** [comment]
@rezamohamed , so, did it work out for you?

**Comment by rezamohamed** [comment]
yes! its been working great albeit its just a small sample project that I am messing around with. I really like it so far, great job!

**Comment by akornich** [comment]
@rezamohamed , glad to hear you started rolling with it.
I am sure the more you use it and learn about it the more you will enjoy it.
Happy Rollbar-ing!

**Comment by rezamohamed** [comment]
feedback: the only thing that I have found is that it would be nice to have some mechanism to delete items in a project/delete all items, kinda like if you want to reset back to a day 0 state. and also, would be nice if it remembers that last dashboard state before logout, right now each time I login I have to check the projects and environments.

**Comment by akornich** [comment]
@rezamohamed , thanks for the feedback. i just forwarded it to our UI team. Best regards!

**Comment by akornich** [comment]
@rezamohamed , can we close this item?

**Comment by rezamohamed** [comment]
yes, please
