### ISSUE TITLE
The type or namespace name 'Report' does not exist in the namespace 'Rollbar' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by VictorioBerra** [rollbar/Rollbar.NET#515]
**Describe the bug**
> The type or namespace name 'Report' does not exist in the namespace 'Rollbar' (are you missing an assembly reference?)

**To Reproduce**

I created a new Core 3.1 app and then installed Rollbar and followed these directions: https://docs.rollbar.com/docs/integrating-with-aspnet-core-2-and-newer

And then in the "Integrate a Notifier" on the Rollbar site, it says "Waiting for data from your ASP.NET app -  MyApp" it says add this code to emit a message: `Rollbar.Report("Rollbar is configured correctly");` that wont compile.

- Core 3.1
```
<PackageReference Include="Rollbar" Version="3.9.1" />
<PackageReference Include="Rollbar.NetCore.AspNet" Version="3.9.1" />
```

**Additional context**

**Comment by akornich** [comment]
Hi @VictorioBerra , 
we do not have such API as Rollbar.Report(...). Current alternatives to sent logs are described in details [here](https://docs.rollbar.com/docs/more-advanced-logger-usages) by using either the shared reusable instance of the RollbarLogger via RollbarLocator or by using scoped (disposable) instances created via RollbarFactory.

**Comment by VictorioBerra** [comment]
![image](https://user-images.githubusercontent.com/2934507/79398818-32ce2e00-7f47-11ea-8b6f-00a56ff5e4ec.png)

**Comment by VictorioBerra** [comment]
Capture didnt come out right but you get the idea. Thanks for the quick reply.

**Comment by akornich** [comment]
@VictorioBerra , our UI engineers looking into it. Thank you!
