### ISSUE TITLE
Version conflict for Microsoft.EntityFrameworkCore.Relational

### ISSUE THREAD

**Issue by skyrawrcode** [rollbar/Rollbar.NET#517]
**Describe the bug**
We have a scenario where we would like to use .Net Core 3.0 but we need to maintain usage of Entity Framework Core 2.x for the time being due to the lack of Oracle drivers.  

**To Reproduce**
1. create .net core 3.0 project
2. install entity framework 2.x
3. Install latest rollbar.net
4. Version conflict detected.

**Expected behavior**
Less reliance on explicit version of entity framework core or no reliance on entity framework core. Ideally the persistence would be a secondary library that could be optionally included.

**Rollbar Client - Rollbar.NET Hosting Environment (please complete the following information):**
 - Rollbar.NET Host type: all
 - OS (all)
 - .net core 3.0
 - Rollbar.NET Version: 3.9.1

**Comment by akornich** [comment]
@skyrawrcode, i am not sure we want to make an official release based on the .net core and ef core versions mismatch. you can probably integrate the SDK into your solution codebase as a git submodule with the customization you need until you are ready to upgrade to the ef core 3.0. 

Making the persistence as a separate and optional module is a more reasonable approach but will require considerable codebase refactoring and at this point, i can not promise how soon or not it can be done.   

Another alternative is - you may want to downgrade to the latest release that did not have persistence (and ef core dependencies) implemented.

**Comment by akornich** [comment]
@skyrawrcode , so are you unblocked for now? can we close this issue?

**Comment by skyrawrcode** [comment]
Yes thank you
