### ISSUE TITLE
A lot of dependencies

### ISSUE THREAD

**Issue by leandrohalfon** [rollbar/Rollbar.NET#519]
Hi!

When i installar the nuget of rollbar it install a lot of dependencies. Its correcto this?

**Comment by akornich** [comment]
@leandrohalfon , the actual amount of dependencies depends upon what SDK package you use to integrate with AND also upon the actual .NET framework target targeted by your application.

In general, we do try to keep these to just the necessary minimum.

**Comment by leandrohalfon** [comment]
Thanks for your quickly answer 😁

I am using framework 4.6.2, for console, mvc AND webforms. What nuget
should i install?

**Comment by akornich** [comment]
@leandrohalfon , you can always start from just Rollbar package it implements all the core functionality. You can either use RollbarLogger directly or as a RollbarTraceListener if you already using .NET trace and trace sources infrastructure.
So, for .NET Framework-based console app the Rollbar package is the way to go.
For the MVC and WebForms you may want to look at Rollbar.Net.AspNet and Rollbar.Net.AspNet.Mvc, they have nice extra goodies relevant to both application frameworks, like HttpContextPackageDecorator, HttpRequestPackageDecorator, HttpResponsePackageDecorator, RollbarHttpModule, ExceptionContextPackage, and RollbarExceptionFilter.

**Comment by akornich** [comment]
no replies for a month. closing...
