### ISSUE TITLE
use HttpClient class

### ISSUE THREAD

**Issue by and-megan** [rollbar/Rollbar.NET#52]
so itt will automatically pick up the proxy configuration from the hosting system.

**Comment by dsutton-aus** [comment]
At the moment, it has been suggested to use the ProxyAddress field (https://github.com/rollbar/Rollbar.NET#rollbarconfig), however, this isn't available to me (v0.3.2);

![image](https://user-images.githubusercontent.com/34899399/34395528-0711e612-ebb5-11e7-9730-c6c037baa9e8.png)

**Comment by akornich** [comment]
@dsutton-aus: are you using Rollbar.NET via NuGet or by getting the codebase directly from GitHub? It looks like NuGet was not updated with the latest code from GitHub yet. The ProxyAddress was added on GitHub on 2017-10-26 while NuGet latest release 0.3.2 was done on 2016-08-10...

**Comment by hanssens** [comment]
Implemented the change from WebClient => HttpClient in PR #54. Hope this helps.

**Comment by dsutton-aus** [comment]
Yes, I’m using Nuget – will download form Github…

**Comment by dsutton-aus** [comment]
I managed to get this to work from behind my corporate firewall by adding DefaultNetworkCredentials, like so;

        private IWebProxy BuildWebProxy()
        {
            if (this.Config != null && !string.IsNullOrWhiteSpace(this.Config.ProxyAddress))
            {
                WebProxy proxy = new WebProxy(this.Config.ProxyAddress);
                proxy.Credentials = System.Net.CredentialCache.DefaultNetworkCredentials;
                return proxy;
            }

            return null;
        }

**Comment by Janek91** [comment]
Can you post updated NuGet package, please?

**Comment by akornich** [comment]
The use of HttpClient is in. It should be able to pick up web proxy server settings from the system. However, you can still explicitly specify the settings via RollbarConfig which will take over the system ones.
