### ISSUE TITLE
RollbarConfig loads native SQLite dlls despite EnablePayloadStore being disabled

### ISSUE THREAD

**Issue by eggersa** [rollbar/Rollbar.NET#528]
We have a lot of issues with the native SQLite dlls which in our case are not required anyway. Since the EnablePayloadStore option is disabled by default, it does not make sense to me that these dlls still get loaded. After investigating the Rollbar.NET code I figured that the SetDefaults method in the RollbarConfig class accesses static fields from the StoreContext class. The static constructor from StoreContext which in turn gets called, tries to load the native SQLite dlls. I think it is not a good idea to do this in the static constructor. Instead the dlls should only get loaded once the payload store is actually being initialized. I am not absolutely sure though if this can be considered a bug or just a feature.

**Comment by akornich** [comment]
@eggersa , thanks for the suggestion! your feedback is much appreciated. we already have some work scheduled in the near future to make the Sqlite dependency option at runtime and to move the payload persistence into an optional SDK extension module.

**Comment by Naatan** [comment]
fyi we had to resort to the downgrade due to this issue, and this is what the diff looked like:

![image](https://user-images.githubusercontent.com/278649/92262542-4e5fb400-eea9-11ea-9d36-9ebe5f988500.png)

You guys might want to reconsider some dependencies.

**Comment by akornich** [comment]
#529 and #558

**Comment by akornich** [comment]
@Naatan , yes we are working on it. please, see #558
