### ISSUE TITLE
Cause of dependencies, could you move offline persistence to another package ?

### ISSUE THREAD

**Issue by jrouaix** [rollbar/Rollbar.NET#529]
**Describe the bug**
As the new versions of rollbar introduce the 'offline persistence' feature (great, we don't use it but great), it also introduce some dependencies to Microsoft.EntityFrameworkCore.Sqlite (distinct versions for distinct targets) ... and that's where something really dirty hit the fan.

**To Reproduce**
1. Have a stable application using entity framework in production, somehow using EF v2 but targeting netcoreapp3
2. Update rollbar to the latest version ...
3. Admire your production exploding with System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.IDbContextOptionsExtensionWithDebugInfo' from assembly 'Microsoft.EntityFrameworkCore, Version=3.0.0.0'

**Expected behavior**
I won't complain about having too much features, no more I'll ask you to get stuck in old dependencies, you already do a great job. But this new feature is an opt-in and could be placed in a optional/plugin nuget package so the ones not using it don't have to support the dependencies burden.

rolled back rollbar package to 3.5.0 and pretty much stuck on it until we migrate our stack to compatible version of entity version or you move these dependencies away. I don't won't to step in some dependency management wizardery if not needed (assembly binding ? don't even know if it would work).

**Comment by akornich** [comment]
@jrouaix , thanks for reporting the issue. yes, we are already scheduling a refactoring work to take payload persistence feature into a separate optional extension module. Please see #523 for details...

**Comment by akornich** [comment]
#528, #558
