### ISSUE TITLE
Instructions for setting up non-MVC project?

### ISSUE THREAD

**Issue by and-megan** [rollbar/Rollbar.NET#53]
hoping to get some guidance on the changes I need to make to the Startup/Configure Services and Startup/Configure methods.

If you are not able to provide the specific changes required for the two methods above, could you at least send through the syntax for the changes to be made in the Program class, keeping in mind this is a netcore app. So my Program file currently looks like this:

public class Program

{

public static void Main(string[] args)

{

BuildWebHost(args).Run();

}

public static IWebHost BuildWebHost(string[] args) =>

WebHost.CreateDefaultBuilder(args)

//.UseKestrel()

//.UseContentRoot(Directory.GetCurrentDirectory())

.UseIISIntegration()

.UseStartup<Startup>()

.Build();

}

**Comment by akornich** [comment]
@and-megan:  Just released v1 has a solution to this one. The instructions are within the Rollbar.NETNotifier.docx (in the root of the codebase). 
Page 11, "Asp.Net Core 2" section has the details. 
@rivkahstandig3636 is working on updating the project front page instructions accordingly.

**Comment by and-megan** [comment]
Hey @akornich I have a user question about the middleware.

"Thanks, I have taken another strategy which provides me with the same outcome (report all unhandled exceptions).

I hook into the app.UseExceptionHandler and send details of the exception from there to Rollbar."

-- is there any difference between using your middleware solution or his above solution?

**Comment by akornich** [comment]
I guess both trying to solve similar problem but slightly differently. Rollbar middleware is custom made Rollbar.NET aware solution. The other one is Asp.Net Core's more generic solution that requires custom action coded to make Rollbar notifications work. Rollbar owns Rollbar middleware code. Microsoft owns the other one. Both would produce similar results if applied similarly.
There are other numerous ways to achieve error handling including writing yet another middleware component if none of the existing ones fit the need. Or, hooking Rollbar into another third party error handling and logging infrastructure like Serilog. At the end, it is an application architect's call what is more appropriate/convinient tool for the job.
