### ISSUE TITLE
Separate ILogger and UnhandledException reporting

### ISSUE THREAD

**Issue by cvallance** [rollbar/Rollbar.NET#533]
**Is your feature request related to a problem? Please describe.**
We use Serilog as our ILogger and we don't really want to replace it with Rollbar or have Rollbar ILogger running along side it either. But I still want Rollbar to report any and all unhandled exceptions.

**Describe the solution you'd like**
It would be great to have a way to configure just the UnhandledException middleware without setting up all the ILogger that is currently coupled with it.

**Describe alternatives you've considered**
I have tried forking and doing it myself but I don't see this as a great long term solution.

There's also the option of using/creating a Serilog sink that sends messages to Rollbar that are at the Error or Critical level.

**Comment by akornich** [comment]
@cvallance , you do not have to use ILogger to use RollbarMiddleware.
Also, we already implement a Serilog sink for Rollbar: RollbarPlugins.Serilog.

**Comment by cvallance** [comment]
Thanks, I'll have a play with that.

**Comment by akornich** [comment]
@cvallance, did our Serilog plug-in work for you? can we close this issue?

**Comment by cvallance** [comment]
No it didn't, but you can close it.

I ended up changing to Raygun, their integration with dotnet aligns more to how I believe things should work. I believe logging and error/unhandled exception reporting to be two separate concerns. Maybe give people the option to combine them if they want (e.g. through a sink like you have), but don't couple them.

**Comment by akornich** [comment]
@cvallance , thanks for the feedback. i think if you set Rollbar log level to error or critical it would address your use case the way you expect.

**Comment by cvallance** [comment]
No it doesn't... I don't want all error logs sent to rollbar.

**Comment by akornich** [comment]
@cvallance , you need more specific custom conditioning regarding what to send vs what not to send to Rollbar, you can always implement your own CheckIgnore delegate.

**Comment by cvallance** [comment]
Sure I could do that... really at the end of the day there's loads of things I could do but at some point you realise that it's much more complicated than it should be and you're investing too much time when you could be working on your own product.
