### ISSUE TITLE
The type initializer for 'NestedSingleInstance' threw an exception.

### ISSUE THREAD

**Issue by aerlijman** [rollbar/Rollbar.NET#534]
**Describe the bug**
I have a solution with many projects in .net 4.6.2 and I want to configure Rollbar in my WebAPI project.
I had to downgrade to 3.5 as I had issues with sql lite
Now, when I try to call RollbarLocator.RollbarInstance.Configure(new RollbarConfig("XXXXXX")); I get the following exception

{
  "Message": "An error has occurred.",
  "ExceptionMessage": "The type initializer for 'NestedSingleInstance' threw an exception.",
  "ExceptionType": "System.TypeInitializationException",
  "StackTrace": "   at Rollbar.RollbarLocator.get_RollbarInstance()\r\n   at SBWebAPI.Controllers.CInvoiceController.RollbarUnhandledExceptionErrorTest(String token) in C:\\Users\\Ariel\\Source\\Repos\\SBWebAPI\\SBWebAPI\\Controllers\\CInvoiceController.cs:line 162\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()",
  "InnerException": {
    "Message": "An error has occurred.",
    "ExceptionMessage": "Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
    "ExceptionType": "System.IO.FileLoadException",
    "StackTrace": "   at Rollbar.NetCore.AppSettingsUtility.LoadAppSettings(String folderPath, String appSettingsFileName)\r\n   at Rollbar.NetCore.AppSettingsUtility.LoadAppSettings(RollbarConfig config)\r\n   at Rollbar.NetStandard.RollbarConfigUtility.Load(RollbarConfig config)\r\n   at Rollbar.RollbarLogger..ctor(Boolean isSingleton, IRollbarConfig rollbarConfig)\r\n   at Rollbar.RollbarFactory.CreateNew(Boolean isSingleton)\r\n   at Rollbar.RollbarLocator.NestedSingleInstance..cctor()"
  }
}

Ideas?

**Comment by aerlijman** [comment]
Additional info: as the error above says...it tries to use Microsoft.Extensions.Configuration 2.0.0 but my projects have 3.1.3

**Comment by akornich** [comment]
@aerlijman , thanks for reporting the issue. It does look like `Microsoft.Extensions.Configuration 2.0.0` dependency issue that causes the exception. I'll try to make a new release this week with the dependency version bumped to v3.

**Comment by aerlijman** [comment]
Thank you for your fast reply. While I was waiting.. I noticed that all my app.config were modified with Rollbar dependencies but my web.config was not! So I copied the changes in my web.config and now it is working!
No idea why the nuget did not add those refs to my web.config
I am using SlowCheeta and have web.config, devweb.conf, etc. But none of them were modified.
No need further action.

**Comment by akornich** [comment]
@aerlijman , thanks for the update. I'll close the issue.
