### ISSUE TITLE
Integrating person data within dotnet core app

### ISSUE THREAD

**Issue by nboltn** [rollbar/Rollbar.NET#545]
How does one go about integrating person data within a dotnet core app? The docs have examples like the following but I don't see how adding static data within a singleton is useful. How do I go about injecting actual user data as requests/errors come in?

```c#
public void ConfigureServices(IServiceCollection services)
{
  ConfigureRollbarSingleton();

  //...
}

/// <summary>
/// Configures the Rollbar singleton-like notifier.
/// </summary>
private void ConfigureRollbarSingleton()
{
  const string rollbarAccessToken = "POST_SERVER_ITEM_ACCESS_TOKEN";
  const string rollbarEnvironment = "RollbarNetSamples";

  RollbarLocator.RollbarInstance
    // minimally required Rollbar configuration:
    .Configure(new RollbarConfig(rollbarAccessToken) { Environment = rollbarEnvironment })
    // optional step if you would like to monitor 
    // Rollbar internal events within your application:
    .InternalEvent += OnRollbarInternalEvent
    ;

    Person person = new Person("123");
    person.Email = "john@doe.com";
    person.UserName = "John Doe";
    RollbarLocator.RollbarInstance.Config.Person = person;
}
```

**Comment by akornich** [comment]
@nboltn, for more dynamic person info capture you can either specify your own payload transformation delegate of the associated RollbarConfig instance and have the person's data captured dynamically at the time of the delegate invocation
OR
every time you prepare payload to log you can add the applicable person's data by using our PersonPackageDecorator. For example,

`            AggregateException exception = 
                new AggregateException("RollbarHttpModule's context error(s)", httpApplication.Context.AllErrors);

            IRollbarPackage package = 
                new ExceptionPackage(exception, "HttpApplication.Context.AllErrors", true);
            
            // The HttpContext decorator already takes care of the HttpRequest and HttpResponse internally:
            package = 
                new HttpContextPackageDecorator(package, httpApplication.Context);

            if (httpApplication.User?.Identity != null && !string.IsNullOrWhiteSpace(httpApplication.User.Identity.Name))
            {
                package = new PersonPackageDecorator(package, httpApplication.User.Identity.Name, httpApplication.User.Identity.Name, null);
            }

            this._rollbar.Error(package);
`

OR 
you can use dedicated RollbarLogger instance (instead of the shared/singleton instance) preconfigured with the relevant person.

**Comment by nboltn** [comment]
thanks for the tips! I think I got something working via payload transformation.

**Comment by akornich** [comment]
@nboltn, you are welcome! can we close the issue now?

**Comment by pbiggar** [comment]
FYI, I couldn't find this info in the Rollbar.NET docs, so this might be worth adding to it.
