### ISSUE TITLE
Add explicit netcoreapp3.1 build framework target

### ISSUE THREAD

**Issue by akornich** [rollbar/Rollbar.NET#560]

**Comment by beeradmoore** [comment]
@akornich , if there was a netcoreapp3.1 target, does this mean we could also replace Newtonsoft.Json with System.Text.Json moving forwards (Maybe at a Rollbar .NET v5)?

**Comment by akornich** [comment]
@beeradmoore, yes, we were looking into switching from Newtonsoft.Json to System.Text.Json eventually. At the same time, we would like to get away from any conditional compilation. I am not sure where the priority should be between the two for now. No promises at this point, but we do evaluate these options periodically.

**Comment by beeradmoore** [comment]
Awesome. Good to hear it hasn't been overlooked.

**Comment by akornich** [comment]
it is already taken care of in v5. closing...
