### ISSUE TITLE
Rollbar.PlugIns.NLog is ignoring environment specific appsettings

### ISSUE THREAD

**Issue by PaloSP** [rollbar/Rollbar.NET#562]
**Describe the bug**
Hi I am using ASP.NET Core 3.1 with NLog and  Rollbar.PlugIns.NLog. I was fallowing this [example](https://github.com/rollbar/Rollbar.NET/tree/master/Samples/Sample.PlugIns.NLog) to set this up. I have two environment specific appsettings.json. One for development (appsettings.development.json) and one for production (appsettings.production.json). I found out that when I specify Rollbar config in currently used appsettings (appsettings.development.json) it is not working. I need to specify this in appsettings.json. So Rollbar is ignoring environment specific appsettings. Is this bug or is this intentional? I would like to set different config for my production and for my development. Is this possible?

**Rollbar Client - Rollbar.NET Hosting Environment (please complete the following information):**
 - Rollbar.NET Host type: web service
 - OS and its version: Windows
 - .NET flavor and its version: .NET Core,
 - Application framework and its version: Asp.NET
 - Rollbar.NET Version: [e.g. 2.1.1]
 - Applicable Rollbar Plug-in (if any): Rollbar.PlugIns.NLog
 - Applicable custom third party logging library/framework integration (if any): NLog,

**Comment by akornich** [comment]
@PaloSP , the Rollbar plug-in for NLog is implemented as an NLog target and works "through" NLog infrastructure that does support development vs production configurations. So, I would expect you to be able to set all the environment-sensitive filters, etc. via NLog itself. On the Rollbar level, you can just specify the delivery/destination settings that are probably common across the environments.

**Comment by PaloSP** [comment]
Thank you very much for the explanation

**Comment by akornich** [comment]
@PaloSP , you are welcome! I hope it unblocked you. Let me know if you have more questions. Otherwise, please, feel free to close the issues.
Best regards!
