### ISSUE TITLE
nearly double Ruby memory usage if 900 Rollbar.error(e) invocations in a few hours

### ISSUE THREAD

**Issue by jpwynn** [rollbar/Rollbar.NET#563]
Is it normal to see huge (nearly double) Ruby memory increase if Rollbar.error(e) is called an average of 6 or 7 times per minute?

Yesterday we started investigating Rollbar (gem 3.0.0) for use with our several Heroku apps. The first guinea pig was a Rails 4.2.11.1 app, Ruby 2.4.5, Puma web server (4.3.6), 3 workers, 1 thread, on Heroku 2X dynos. 

In our evaulation, we enabled Rollbar.error(e) in several places, including some benign-exception 'rescue'  blocks that are invoked frequently. This generated about 800 Rollbar events over a 2 hour period (average 6 per minute). And our max-memory nearly doubled from 675MB to 1150MB.

To my surprise, the use of Rollbar.error(e) seems to correlate with very significant memory bloat in Ruby memory.

So it seems even "swallowed" exceptions that would otherwise have no zero impact on user experience will significantly degrade user experience if Rollbar is enabled triggered an average of every 10 seconds.

To be precise, the benign exceptions do not, absent Rollbar, increase app memory use, which you can see in the Heroku memory metric screenshot attached, which shows the two hours before-and-after setting Rollbar's config.enabled to false ... the memory increase did _not_ re-occur under _similar_ traffic conditions once we disabled Rollbar by setting config.enabled = false

Heroku memory use before and after disabling rollbar:
<img width="248" alt="g1" src="https://user-images.githubusercontent.com/446451/93385359-df1b8580-f801-11ea-973a-4c0041a7c1a3.png">

Same timeframe (slightly different scale): Rollbar activity:
<img width="193" alt="g2" src="https://user-images.githubusercontent.com/446451/93385504-10945100-f802-11ea-8029-f709dfc0a77f.png">

**Comment by akornich** [comment]
@jpwynn , are you sure this is the correct SDK/repo to report Ruby-related issues :) ?

**Comment by jpwynn** [comment]
ah, didnt notice it was .net sorry.
