### ISSUE TITLE
Add ILogger LoggerName to details in Rollbar

### ISSUE THREAD

**Issue by JohnCampionJr** [rollbar/Rollbar.NET#564]
**Is your feature request related to a problem? Please describe.**
I cannot always tell where an event is coming from in Rollbar.

**Describe the solution you'd like**
It would be very useful if Rollbar would include the loggername from the .Net Core ILogger interface

**Comment by akornich** [comment]
@JohnCampionJr , thanks for the suggestion! I'll try to add it in sometime this month.

**Comment by akornich** [comment]
@JohnCampionJr , it is really odd - I can not find ILogger defining its Name property despite the fact that it what I think I remembered about .Net Core logger having that property. 
However, we do have Name property on our RollbarLogger (that implements .Net Core's ILogger) does have this property defined. So, I am adding this property value to the log payload whenever it is assigned.
