### ISSUE TITLE
EnableRewind vs EnableBuffering

### ISSUE THREAD

**Issue by Lobosque** [rollbar/Rollbar.NET#570]
https://github.com/rollbar/Rollbar.NET/blob/cde25f5517999115df8fc2a84a25fb1eda27960c/Rollbar.NetCore.AspNet/RollbarMiddleware.cs#L93

Is this taking into account .NET5?

**Comment by akornich** [comment]
@Lobosque , I believe so, since we are not explicitly building .NET 5 targets yet and .NET 5 should be compatible with .NET Standard 2.1.

**Comment by Lobosque** [comment]
@akornich I use the default middleware but I never get any request data (payload) on rollbar.
I understand this is supposed to include this data?

**Comment by akornich** [comment]
@Lobosque , yes, if an HTTP request's data is expected to be added to a corresponding payload created by the middleware. So, you are saying you are getting payloads transferred to Rollbar.com (Project Dashboard) but without the request data attached?

**Comment by akornich** [comment]
closing due to no response
