### ISSUE TITLE
Do we support WebForms?

### ISSUE THREAD

**Issue by and-megan** [rollbar/Rollbar.NET#58]
Does this library currently support ASP.NET WebForms? 

@akornich we were chatting about this yesterday in Slack. I'll post the relevant bits of info: 
In general, I think the Rollbar.NET should work within a WebForms app. But that is assuming that WebForms are still supported by .NET 4.5 (that is oldest .NET version that Rollbar.NET v1 supports)
Let me research if the WebForms are still part of latest .NET frameworks.

**Comment by akornich** [comment]
just some sources to research:
[https://msdn.microsoft.com/en-us/library/hh420390(v=vs.110).aspx](url)

**Comment by akornich** [comment]
yes, we do. starting v1.0.0.

**Comment by supergibbs** [comment]
Updated sample link:  https://github.com/rollbar/Rollbar.NET/tree/master/Samples/Sample.WebForms.Site
