### ISSUE TITLE
Make Serilog Plugin Support Appsettings Configuration

### ISSUE THREAD

**Issue by TheWix** [rollbar/Rollbar.NET#586]
**Is your feature request related to a problem? Please describe.**
I am able to configure Rollbar with appsettings but not the Serilog plugin. This is unfortunate because all the other Serilog Sinks we use are configured in the appsettings

**Describe the solution you'd like**
Make the Serilog Plugin work with serilog-settings-configuration so it is easier to configure based on environment

**Describe alternatives you've considered**
I am using the code-based configuration but this is not ideal since all our other sinks use appsettings.

If this is already supported I was unable to locate the documentation around it.

**Comment by akornich** [comment]
@TheWix , yes, that would be a useful feature to add. Let me see what level of priority it can get. We are in process of planning for Q3. Maybe we can fit it in...

**Comment by glen-84** [comment]
@akornich Any updates here? I'd really prefer to configure the sink using `appsettings.json`.

**Comment by mthgr** [comment]
Is there any progress on this feature, or is it planned for release? All our other Serilog sinks are using appsettings (as mentioned by someone else in this thread), and this seems like a common scenario. It would be extremely useful.

**Comment by rollbar-bborsits** [comment]
Hey Folks, Thanks for raising this feature request. I moved it to our Idea backlog. Unfortunately, this feature isn't expected soon, but we might pick it up later. I'll go ahead and close this issue for now.
