### ISSUE TITLE
Update Rollbar.NET's dependency on Newtonsoft.Json package to current version 13.0

### ISSUE THREAD

**Issue by dchasman** [rollbar/Rollbar.NET#587]
I just spent an insane amount of time figuring out why my items were not being sent from our C# app (async .Error()/Info() etc silently failed - switched to AsBlockingLogger() and finally saw the failure (nested exception where the deepest one was an asseembly load failure on Newtonsoft.Json dll).

Our application depends on Newtonsoft.Json version 13 and there are known compatibility issues with using bindingRedirects etc to address this since .NET assembly versioning was not handled correctly by Newtonsoft.Json - and Assembly.LoadFrom() is also a non starter:

https://stackoverflow.com/questions/31608983/newtonsoft-json-net-version-incompatibility-dll-hell

I am at the point where I have locally upgraded the Newtonsoft.Json package and built from Rollbar source and am now able to keep moving. Do you want a pull request for this?

**Comment by akornich** [comment]
Hi @dchasman , the SDK targets multitude of .NET frameworks, versions, and application frameworks. The reason we are staying on a bit outdated version of Newtonsoft.Json is to support compatibility with a large collection of targets as possible.
We most likely will be doing soon the next assessment of the targets we support. Depending on the outcome we may be able to bump Newtonsoft version a bit up. 
BTW, when you suspect "silent failures" or any time you suspect the SDK does not behave the way you expect, try subscribing to the SDK internal events to gain insights into what actually could be happening (https://docs.rollbar.com/docs/monitoring-the-sdk-internal-events).
And you should definitely use a blocking logger when calling the SDK on the application exit or inside an application last-chance unhandled exception handler.

**Comment by dchasman** [comment]
@akornich thank you for responding so quickly! 

Understood on the massive number of targets - it’s obvious when you build Rollbar from source that there are a ton :-)

In our case we’re logging handled/recoverable exceptions so we’ve avoided synchronous notifications. I’ll definitely look into switching our last chance logic and app exit to sync.

I will try subscribing to internal events - I’m curious if this type of low level, unable to init a class/load an assembly, will actually be surfaced. Regardless this event stream will be useful for a number of things I’m sure.

**Comment by dchasman** [comment]
Thank you @akornich !
