### ISSUE TITLE
Rollbar.Init doesn't exist

### ISSUE THREAD

**Issue by Meerkat66** [rollbar/Rollbar.NET#59]
Hi, I was using v0.3.2 with great success and then updated to v1.0.0, however the function 'Rollbar.Init' no longer seems to exist.  The documentation on the main page still lists it as the main function to use so I assume it still exists somewhere, could you point me in the right direction for this please?

**Comment by rivkahstandig3636** [comment]
Hi there, Yes, check out the PR I have open with the updated docs [here](https://github.com/rollbar/Rollbar.NET/pull/57). The upgrading specific instructions can be found [here](https://github.com/rollbar/Rollbar.NET/blob/94f1346a2143b3e565ca60e3d10618b594482af8/README.md#upgrading-to-v100-from-earlier-versions). Sorry for the confusion!
