### ISSUE TITLE
.NET v5 docs say to configure access token twice?

### ISSUE THREAD

**Issue by Daniel15** [rollbar/Rollbar.NET#591]
https://docs.rollbar.com/docs/v5-integrating-with-aspnet-core-2-and-newer says to configure the access token in two places:
- On the `RollbarInfrastructureConfig`
- In either `appsettings.json` or `ConfigureServices`

Is it really necessary to do this twice?

**Comment by akornich** [comment]
It is "either ... or ...". It looks like some older v4 instructions leaked into v5 docs. I was doing "copy, paste, and update" v5 docs based on v4 docs and missed intended cleanup of the old content. Just updated the doc.
Thanks for reporting it!
