### ISSUE TITLE
Question: How to use People Tracking in Asp Net Core 5 Web app

### ISSUE THREAD

**Issue by januszj** [rollbar/Rollbar.NET#602]
What is recommended way to enable People Tracking in Asp Net Core 5 Web app
I used this guide to setup integration: https://docs.rollbar.com/docs/v5-integrating-with-aspnet-core-2-and-newer
It can't done in initialization as this executed only once when app in starting.

Application is using build in Identity, so I'm using: 
```
string userId = User.Identity.Name; 
```
in Controllers, to get e-mail address/id of current user. This is centralized in my code.
So this would be the place to inject person data into Rollbar.

**Rollbar Client - Rollbar.NET Hosting Environment (please complete the following information):**
 - Rollbar.NET Host type: web service
 - OS and its version: windows
 - .NET flavor and its version: .NET Core, 
 - Application framework and its version: Asp.NET
 - Rollbar.NET Version: 5.0.4-beta
 - Applicable Rollbar Plug-in (if any): 
 - Applicable custom third party logging library/framework integration (if any): 
 - Applicable Browser (if any): [e.g. chrome, safari]

**Comment by akornich** [comment]
@januszj , you can always create an instance of the RollbarLogger in your controller and build a package to send to Rollbar right there with all customization you need. For example, by applying PersonPackageDecorator (with the captured user info) to the package to send.
Does it fully answer your question?

**Comment by januszj** [comment]
Thanks @akornich I will try this
