### ISSUE TITLE
No option to set code_version at the config level in v5 of the SDK

### ISSUE THREAD

**Issue by tattan** [rollbar/Rollbar.NET#630]
**Is your feature request related to a problem? Please describe.**
In v4 of the SDK this issue was created https://github.com/rollbar/Rollbar.NET/issues/13 and fixed. I was looking for a way to do that or something similar in v5 of the SDK

**Describe the solution you'd like**
I'd like to be able to include code_version (not server code_version) at either the RollbarInfrastructureConfig or RollbarLoggerConfig. 

**Describe alternatives you've considered**
Having a custom wrapper that takes a Body and sets the version for each rollbar item to be sent.

**Comment by akornich** [comment]
@tattan , actually it looks like #13 and #14 happened during v0 of the SDK.
Let me see what we can do here...

**Comment by akornich** [comment]
@tattan , for now, you can probably define your own payload transform action (here)[https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar/Config/RollbarPayloadManipulationOptions.cs#L42] so you can assign the desired code version to every processed payload...

**Comment by akornich** [comment]
@tattan , now as a long-term solution, what if I add new nullable CodeVersion property [here](https://github.com/rollbar/Rollbar.NET/blob/master/Rollbar/Config/RollbarPayloadAdditionOptions.cs#L13) and will be assigning to every payload's `Data.CodeVersion` if defined (not null)?

**Comment by tattan** [comment]
@akornich I think your long-term solution would be great. I'll implement a transform in the meantime.

**Comment by DrewSaucier** [comment]
@akornich do you have a timeline on this request.  We are bumping up against as well in v4 to v5 updating.

Thank you!

**Comment by akornich** [comment]
> 

@DrewSaucier , I'll try to have it out sometime this week.

**Comment by akornich** [comment]
now available in v5.2.0...

**Comment by tattan** [comment]
Hi @akornich, the proposed solution was implemented to spec but did not have the same effect as setting `code_version` in the root of the json body.

Setting `notifier.infrastructure_options.RollbarloggerConfig.RollbarPayloadAdditionOptions.CodeVersion` and `notifier.configured_options.RollbarPayloadAdditionOptions.CodeVersion` does not update the github (in our case) link displayed in the code_version column. 

For now we are continuing to use a transform to achieve the desired result but I wanted to know if your intent was to have the sha sum set correctly and the link to source control generated when a given occurrence is sent as it is if you send a sha value for `code_version` in the root of the payload.

**Comment by DrewSaucier** [comment]
Thank you!

Drew Saucier
Vice President
Paul Consulting Group
Direct 850-610-6964
Cell 850-251-1389
