### ISSUE TITLE
Could not load type 'Rollbar.RollbarLocator' from assembly 'RollBar, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by RollbarExample** [rollbar/Rollbar.NET#70]
Hi,

I am facing the problem while integrating the Rollbar into my ASP.NET MVC project.
I have followed the documentation instructions that you have provided.

Here is the step that I have followed.
1. Installed rollbar package- Install-Package Rollbar -Version 1.0.1 
2. Configure rollbar into the global.asax.cs
```
protected void Application_Start()
        {
            const string postServerItemAccessToken = "MY_ACCESS_TOKEN";
            RollbarLocator.RollbarInstance.Configure(new RollbarConfig(postServerItemAccessToken)
            {
                Environment = "production"
            });
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
        }
```
I am getting the following error while application loading.

![capture](https://user-images.githubusercontent.com/32199575/35054173-f7d8fb68-fbd1-11e7-85e1-79da8241fe1b.PNG)

Could you please help me out.

**Comment by akornich** [comment]
Please, make sure you have Rollbar.dll in you application execution directory (working directory).

**Comment by RollbarExample** [comment]
@akornich yes i can see the Rollbar dll in my project.

![capture](https://user-images.githubusercontent.com/32199575/35097198-2c8e1ec6-fc75-11e7-8cd4-44f2129b6062.PNG)

**Comment by akornich** [comment]
thanks! that is your design time view of the project in visual studio and everything looks correct. as you can see the class in question is recognized correctly by the visual studio (no red wavy line under RollbarLocator in the text editor). however, you do have runtime problem. please, locate your build output directory (usually, called "bin") and verify that you do have correct version of Rollbar.dll there.

also, you might want to run "dotnet restore" command in your nuget management console on the whole solution and do a clean rebuild of everything.

the fact that you mention that you are using rollbar.net v1.0.1 but the exception mentions v1.0.0 leads me me to believe you have some stale build or package state or both.

btw, once you resolve this runtime issue, do not forget to specify a valid access token in your code...

**Comment by akornich** [comment]
@RollbarExample , is this still an issue?

**Comment by RollbarExample** [comment]
@akornich  Thanks that issue has been resolved. Now I can able to send the crash log on the rollbar dashboard.

**Comment by akornich** [comment]
@RollbarExample , you are welcome. closing it, then.
