### ISSUE TITLE
Support for netstandard1.x

### ISSUE THREAD

**Issue by luisrigoni** [rollbar/Rollbar.NET#76]
Would be nice to have support to netstandard1.x also.

I can't update my 1.4 project because of another dependencies which are not compatible with 2.x (private library and closed-source...).

**Comment by akornich** [comment]
Did you actually try moving your codebase from netstandard 1.x to 2.0? As I understand netstandard keeps growing a toolbox of its APIs from version to version, so normally, each newer version of the standard is a superset of previous ones. So, technically, there was nothing removed from APIs in 2.0 compare to 1.x. Hence you should be able to move forward safely.

**Comment by luisrigoni** [comment]
The problem is that dependency (private and closed-sourced) is distributed as a Nuget package at MyGet and only to netstandard1.4. When I try updating my project  to netstandard2.x the Package Manager fail saying it cannot be done because one dependency is not available to netstandard2.x.

**Comment by akornich** [comment]
Strange, normally I would expect the PackageManager to still take 1.4 version and put out a warning but not a hard error. Is there possibility to request the component provider to target netstandard 2.0 side by side with 1.4 and build both into their NuGet package? It should be just a project file settings change and rebuild/repackage with no other actual source code changes.

**Comment by akornich** [comment]
We do support similar multi-targeting of Rollbar.NET Notifier: netstandard2.0 and up, netcoreapp2.0 and up, net4.5 and up. netstandard1.x and netcoreapp1.x had very limited (not prime time ready in my opinion) functionality with lot of APIs missing (for example, some basic reflection and diagnostics types are missing). Adding support for <2.0 would mean adding conditional compilation control with source code branches of conditioning following significantly different designs and giving up on some features.

**Comment by luisrigoni** [comment]
> Adding support for <2.0 would mean adding conditional compilation control with source code branches of conditioning following significantly different designs and giving up on some features.

Regarding any consideration, losing features don't seems reasonable and a good argument to not target netstandard1.x.
