### ISSUE TITLE
.NET not logging since update to 1.0.1 via nuget

### ISSUE THREAD

**Issue by dsutton-aus** [rollbar/Rollbar.NET#78]
I have started a brand new, never touched before, test project. Then added the later Rollbar nuget package 1.0.1. I’m following docs from here: https://rollbar.com/docs/notifier/rollbar.net/

I have stripped my nunit test right back to this;

using NUnit.Framework;
using Rollbar;
using System;

namespace RollbarTests
{
    [TestFixture]
    public class SmokeTests
    {
        private string apiKey = "myApiKey";

        [Test]
        public void JustLog()
        {
            RollbarLocator.RollbarInstance.Configure(new RollbarConfig(apiKey) { Environment = "development" });

            Assert.DoesNotThrow(() => RollbarLocator.RollbarInstance.Info(string.Format("Logging test {0:dd MMM yyyy HH:mm:ss:ffff}", DateTime.Now)));
        }
    }
}

No errors are generated, yet nothing is logging (I have tried both server-side and client-side apiKeys). I'm not behind a firewall for this test, and I can ping api.rollbar.com.

What am I missing?

**Comment by akornich** [comment]
@dsutton-aus, did you try subscribing to the RollbarInstance's InternalEvent to see what internal events/errors are generated during your use case?

**Comment by dsutton-aus** [comment]
Thanks, adding Thread.Sleep does enable logging again. I'm keen to see v1.0.2

**Comment by akornich** [comment]
@dsutton-aus: v1.0.2 is available via GitHub or NuGet...

**Comment by rivkahstandig3636** [comment]
@dsutton-aus Please let us know if v1.0.2 has solved this issue for you. :)

**Comment by dsutton-aus** [comment]
I've updated to 1.0.2 - I still need to add Thread.Sleep in order for the error to log.

I thought it may be related to my test project targetting 4.5.1, so I have also updated to 4.6.1 and reinstalled the 1.0.2 Nuget package. I'm scratching my head a bit - any more advice?

**Comment by akornich** [comment]
@dsutton-aus, are you using blocking calls like this?:
try
            {
                RollbarLocator.RollbarInstance.AsBlockingLogger(TimeSpan.FromMilliseconds(10000))
                    .Info("Via blocking mechanism.")
                    ;
            }
            catch (System.TimeoutException ex)
            {
                msg = "*** Blocking call with too short timeout. Exception: " + Environment.NewLine + ex;
                System.Diagnostics.Trace.WriteLine(msg);
                Console.WriteLine(msg);
            }

**Comment by akornich** [comment]
any ILogger interface defines now AsBlockingLogger(TimeSpan timeout) method that returns blocking ILogger implementation that uses provided timeout when things go wrong. so, it either succeeds in sending the payload in synchronous fashion within the specified timeout interval or ends with a timeout exception due to the timeout.

**Comment by akornich** [comment]
@dsutton-aus, did the last advice help you?

**Comment by dsutton-aus** [comment]
Sorry @akornich, I've just tested again. I seem to have lost logging ability completely so unable to test.

**Comment by akornich** [comment]
@dsutton-aus, may i ask you to post the code snippet of how you initialize, configure and use the notifier?

**Comment by jonathanjto** [comment]
Hello there, 

I've the same problem. In ASP.NET MVC app logging is fully functionnal but in WinForm and ConsoleApp nothing works anymore ...

```
string postServerItemAccessToken = ConfigurationManager.AppSettings["ROLLBAR_ACCESSTOKEN"];
RollbarLocator.RollbarInstance.Configure(new RollbarConfig(postServerItemAccessToken));
RollbarLocator.RollbarInstance.InternalEvent += OnRollbarInternalEvent;
RollbarLocator.RollbarInstance.Info("TESSSST");
```

Implementation of the OnRollbarInternalEvent is never call.

**Comment by akornich** [comment]
@jonathanjto, it looks like your winforms and console apps terminate/exit before the background thread of the rollbar notifier has chance to process the queued up info message. And you did the right thing by switching to a blocking call in that scenario. And i believe when using the blocking call the InternalEvent is also raised as expected.
When you log irrecoverable exceptions when your application is about to terminate due to the exception, always using blocking logging. In the cases when processing non-terminal errors (that do not cause termination of the application process) - use non-blocking methods.

**Comment by akornich** [comment]
@dsutton-aus and @jonathanjto, so, gentlemen, are you unblocked by now?

**Comment by jonathanjto** [comment]
Yes, it's working without problem.

Sorry for the delay but i just wanted to verify something.

You should add this information in the "Upgrading to v1.0.0+ from earlier versions" section part of the documentation. This is a pretty huge change and this is not highlighted in this section, you should at least refers to the section https://github.com/rollbar/Rollbar.NET#blocking-vs-non-blocking-use.

Thanks for you help.
Best regards,

**Comment by akornich** [comment]
@jonathanjto, thanks for the update!
I am glad it all worked out for you (as expected :).
Thanks for the suggestion. We will definitely update the documentation to highlight the difference from pre-v1 behaviour.
BTW, v1.0.3 will be coming out this week...
