### ISSUE TITLE
Support for Asp.net Core

### ISSUE THREAD

**Issue by Tiger333** [rollbar/Rollbar.NET#8]
Does this library support asp.net core 1.1?

**Comment by drnluz** [comment]
I'm trying to use it with ASP.NET core 2.0 and it seems to work despite the following warning:

```
Warning NU1701: Package 'Rollbar 0.3.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. (NU1701)
```

**Comment by rokob** [comment]
Yeah we definitely should support this and it is on the roadmap for the new v1 release we are working on which will be tracked here https://github.com/rollbar/Rollbar.NET/milestone/1

**Comment by akornich** [comment]
this should not be an issue once v1 is out. btw, .NETCoreApp2.0 is already supported in the v1-alpha.

**Comment by akornich** [comment]
.net core 2.0 is currently supported in:
[https://github.com/WideSpectrumComputing/Rollbar.NET/tree/v1](url)
Supporting .net core prior to 2.0 will require conditionally compiled code changes. 
@rokob, @coryvirok, @jessewgibbs : 
Do we want to support .net core older than v2.0? 
BTW, the same goes for Full .NET older than v4.5.

**Comment by akornich** [comment]
I am closing this item since we already have a superset of this issue addressed by:
[https://github.com/rollbar/Rollbar.NET/issues/34](url)
