### ISSUE TITLE
Implement Microsoft.Extensions.Logging.ILogger

### ISSUE THREAD

**Issue by patoncrispy** [rollbar/Rollbar.NET#87]
I'm not sure if this has been discussed yet but I was wondering if it would be possible for Rollbar.Net to implement `Microsoft.Extensions.Logging.ILogger` for .NET Core apps? 

The benefits:

👍  Works with .NET Core DI out of the box.
👍  Can be used with ILoggerProvider and ILoggerFactory in order to more seamlessly co-exist with other logging approaches (text file, database, etc.).
👍 Removes frustrating conflict between `Microsoft.Extensions.Logging.ILogger` and `Rollbar.ILogger`.
👍  No more static classes (making code easier to test)!

**Comment by akornich** [comment]
@patoncrispy, thanks for the ideas!

yes, we are considering adding extensions/plug-in to major and popular logging frameworks and libraries (from .NET trace listeners to log4net, log.net, etc.).

for .net core specifically we do already have a Rollbar extension implemented as asp.net core middleware which greatly simplifies its use (just add .UseRollbar() and configure it appsettings file or in code).

meanwhile, use of "using aliases" easily solves ILogger name conflict inconveniences like this ms.Ilogger vs rb.ILogger.

as of v1, Rollbar notifier is no longer a static implementation. it support multiple instances (via RollbarFactory) use cases as well as application wide service like use case where it is implemented as a singleton.

**Comment by StefanoChiodino** [comment]
Would be good to have examples of this. Can't find anything and I've been trying for one hour unsuccessfully.

**Comment by akornich** [comment]
@StefanoChiodino , I assume your question is about Rollbar.NET integration with an Asp.Net Core application. Here is an example:

**Comment by StefanoChiodino** [comment]
@akornich thanks, but I have:
```
            var rollbarKey = configuration.GetSection("RollbarKey").Value;
           
            var rollbar = RollbarLocator.RollbarInstance
                .Configure(new RollbarConfig(rollbarKey)
                    {Environment = Environment.MachineName});

            services.AddRollbarLogger(loggerOptions =>
            {
                loggerOptions.Filter = (loggerName, loglevel) => loglevel >= LogLevel.Warning;
            });
```
and when I try to inject Microsoft's ILogger into a hangfire task I get
```
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'MyProject.Web.MonitoringJob'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
```

**Comment by StefanoChiodino** [comment]
With the code above I can't even get a Rollbar own ILogger! I've added
```

            services.AddSingleton(rollbar.Logger);
            services.AddSingleton(rollbar.AsBlockingLogger(TimeSpan.Zero));

            var rollbarOptions = new RollbarOptions();
            rollbarOptions.Filter = (s, level) => level >= LogLevel.Warning;
            services.AddSingleton(rollbarOptions);
            
            services.AddSingleton(x => x.GetService<RollbarLoggerFactory>().CreateLogger(""));
```
to it, which is probably way overkill, but at least now I can get Rollbar ILogger!

**Comment by akornich** [comment]
@StefanoChiodino , all you need to do is:
1. install Rollbar Nuget package into your Asp.Net Core project
2. add at the top of Startup.ConfigureServices(...):

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            ConfigureRollbarSingleton();

            services.AddRollbarLogger(loggerOptions =>
            {
                loggerOptions.Filter = (loggerName, loglevel) => loglevel >= LogLevel.Trace;
            });
where 
        private void ConfigureRollbarSingleton()
        {
            const string rollbarAccessToken = "17965fa5041749b6bf7095a190001ded";
            const string rollbarEnvironment = "RollbarNetSamples";

            RollbarLocator.RollbarInstance
                // minimally required Rollbar configuration:
                // if you remove line below the logger's configuration will be auto-loaded from appsettings.json
                .Configure(new RollbarConfig(rollbarAccessToken) { Environment = rollbarEnvironment })
                // optional step if you would like to monitor Rollbar internal events within your application:
                .InternalEvent += OnRollbarInternalEvent
                ;
        }

and (if you want to monitor Rollbar SDK internal events)

        private static void OnRollbarInternalEvent(object sender, RollbarEventArgs e)
        {
            Console.WriteLine(e.TraceAsString());

            RollbarApiErrorEventArgs apiErrorEvent = e as RollbarApiErrorEventArgs;
            if (apiErrorEvent != null)
            {
                //TODO: handle/report Rollbar API communication error event...
                return;
            }
            CommunicationEventArgs commEvent = e as CommunicationEventArgs;
            if (commEvent != null)
            {
                //TODO: handle/report Rollbar API communication event...
                return;
            }
            CommunicationErrorEventArgs commErrorEvent = e as CommunicationErrorEventArgs;
            if (commErrorEvent != null)
            {
                //TODO: handle/report basic communication error while attempting to reach Rollbar API service... 
                return;
            }
            InternalErrorEventArgs internalErrorEvent = e as InternalErrorEventArgs;
            if (internalErrorEvent != null)
            {
                //TODO: handle/report basic internal error while using the Rollbar Notifier... 
                return;
            }
        }

3. within Startup.Configure(...), add
            app.UseRollbarMiddleware();
right before app.UseMvc(...) call

4. in every controller add 

        private readonly ILogger _logger = null;
        private readonly IHttpContextAccessor _httpContextAccessor = null;

        public MyController(ILogger<HomeController> logger, IHttpContextAccessor httpContextAccessor)
        {
            this._logger = logger;
            this._httpContextAccessor = httpContextAccessor;
        }
5. at this point any http request processing logging info will be forwarded to Rollbar API.
6. to add custom/extra logging calls do something like this within MyController:
        public IActionResult Index()
        {
            this._logger.LogCritical(nameof(MyController) + ".Get() is called...");

            return View();
        }

7. if you wits to drive your Rollbar configuration from appsettings.json, add to its root:

  "Rollbar": {
    "AccessToken": "17965fa5041749b6bf7095a190001ded",
    "Environment": "RollbarNetSamples",
    "Enabled": true,
    "MaxReportsPerMinute": 160,
    "ReportingQueueDepth": 120,
    "LogLevel": "Info",
    "ScrubFields": [
      "ThePassword",
      "TheSecret"
    ],
    "Person": {
      "UserName": "jbond",
      "id": "007"
    }
  },

and remove:
            const string rollbarAccessToken = "17965fa5041749b6bf7095a190001ded";
            const string rollbarEnvironment = "RollbarNetSamples";

            RollbarLocator.RollbarInstance
                // minimally required Rollbar configuration:
                // if you remove line below the logger's configuration will be auto-loaded from appsettings.json
                .Configure(new RollbarConfig(rollbarAccessToken) { Environment = rollbarEnvironment })
from the ConfigureRollbarSingleton() implementation.

**Comment by StefanoChiodino** [comment]
Thanks, I think the problem was that I was using `ILogger` instead of `ILogger<>`!

**Comment by akornich** [comment]
@StefanoChiodino , you are welcome!
