### ISSUE TITLE
Cannot Integrate a Notifier to .Net Core App 2.0

### ISSUE THREAD

**Issue by pranithan-kang** [rollbar/Rollbar.NET#88]
I newly created the experimental .Net Core App 2.0 Console project with Rollbar installed. And write the code

``` C#
using Rollbar;
using System;

namespace RollbarExper
{
    class Program
    {
        static void Main(string[] args)
        {
            RollbarLocator.RollbarInstance.Configure(
                new RollbarConfig("{ACCESS_TOKEN}")
                {
                    Environment = "production"
                }
            );
            RollbarLocator.RollbarInstance.Info("Rollbar is configured properly.");
            try
            {
                int value = 1 / int.Parse("0");
                //string n = null;

                //n.ToUpper();
            }
            catch (System.Exception ex)
            {
                RollbarLocator.RollbarInstance.Error(ex);
            }
        }
    }
}
```
I successfully ran the application.
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/5810073/36463141-6edccd1e-16fa-11e8-8d0d-99b2560cff1d.PNG">

 However, the web page project is not seem to receive any error.
<img width="887" alt="capture" src="https://user-images.githubusercontent.com/5810073/36463041-d4df1eb0-16f9-11e8-9164-933dd6a355ce.PNG">

**Comment by pranithan-kang** [comment]
After I then tried the same thing with .Net Framework and successfully get the Exception tracked in the web page. So, I use Fiddler to investigate what is actually happened with .Net Framework and .Net Core App. Finally, I found that in .Net Core App I have to manually set the Endpoint to `https://api.rollbar.com/api/1/` to get the Exception sending to the web page successfully.

``` C#
using Rollbar;
using System;

namespace RollbarExper
{
    class Program
    {
        static void Main(string[] args)
        {
            RollbarLocator.RollbarInstance.Configure(
                new RollbarConfig("{ACCESS_TOKEN}")
                {
                    Environment = "production", 
                    EndPoint = "https://api.rollbar.com/api/1/" // Add this parameter
                }
            );
            RollbarLocator.RollbarInstance.Info("Rollbar is configured properly.");

            try
            {
                Console.WriteLine("In exception try..");

                //int value = 1 / int.Parse("0");

                string n = null;
                n.ToUpper();
            }
            catch (System.Exception ex)
            {
                Console.WriteLine("In exception catch..");
                RollbarLocator.RollbarInstance.Error(ex);
            }
            finally
            {
                Console.ReadKey();
            }
        }
    }
}
```

**Comment by pranithan-kang** [comment]
After I then tried the same thing with .Net Framework and successfully get the Exception tracked in the web page. So, I use Fiddler to investigate what is actually happened with .Net Framework and .Net Core App. Finally, I found that in .Net Core App I have to manually set the Endpoint to `https://api.rollbar.com/api/1/` to get the Exception sending to the web page successfully.

``` C#
using Rollbar;
using System;

namespace RollbarExper
{
    class Program
    {
        static void Main(string[] args)
        {
            RollbarLocator.RollbarInstance.Configure(
                new RollbarConfig("{ACCESS_TOKEN}")
                {
                    Environment = "production", 
                    EndPoint = "https://api.rollbar.com/api/1/" // Add this parameter
                }
            );
            RollbarLocator.RollbarInstance.Info("Rollbar is configured properly.");

            try
            {
                Console.WriteLine("In exception try..");

                //int value = 1 / int.Parse("0");

                string n = null;
                n.ToUpper();
            }
            catch (System.Exception ex)
            {
                Console.WriteLine("In exception catch..");
                RollbarLocator.RollbarInstance.Error(ex);
            }
            finally
            {
                Console.ReadKey();
            }
        }
    }
}
```

**Comment by akornich** [comment]
@pranithan-kang, either add call to Console.ReadKey() the same way you have it in your working .NET Framework example or use RollbarLocator.RollbarInstance.AsBlockingLogger(timeout).Error(ex);
Your .NET Core sample app exits/terminates process before Rollbar.NET has chance to transmit the log message...

**Comment by akornich** [comment]
the ILogger interface defines now AsBlockingLogger(TimeSpan timeout) method that returns blocking ILogger implementation that uses provided timeout when things go wrong. so, it either succeeds in sending the payload in synchronous fashion within the specified timeout interval or ends with a timeout exception due to the timeout.
