### ISSUE TITLE
Package issue with .NET Core

### ISSUE THREAD

**Issue by motiejunas** [rollbar/Rollbar.NET#9]
I can't install Rollbar.NET NuGet package:
> Installing Rollbar 0.3.2.
> Package Rollbar 0.3.2 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Rollbar 0.3.2 supports: net45 (.NETFramework,Version=v4.5)

**Comment by rokob** [comment]
I think this has to do with the way our package is configured against certain frameworks, we are planning support for .net core as part of the upcoming v1 release.
