### ISSUE TITLE
Support delayed Configure(config), especially with Person

### ISSUE THREAD

**Issue by buzzware** [rollbar/Rollbar.NET#97]
I see the Reconfigurable config class, but I don't think the code is currently using the reconfigured event to update. My use case is that I set up the client before the user is logged in, then when it is logged in, I need to set the Person properties.

I'm doing :

```
var config = Rollbar.RollbarLocator.RollbarInstance.Config;
var rbPerson = new Rollbar.DTOs.Person()
{
	Id = person==null ? FreeCommon.Platform?.uniqueDeviceId.ToString() : person.identt_id.ToString(),
	UserName = person?.fullName ?? person?.identt_id.ToString(),
	Email = FreeCommon.Token?.user_name
};
config.Person = rbPerson;
Log.Debug("Update Rollbar Person to: " + FreeCommon.Json.Serialize(rbPerson));
Rollbar.RollbarLocator.RollbarInstance.Configure(config);				

```

**Comment by akornich** [comment]
@buzzware, are you experiencing any issue while assigning new Person object as post initial configuration step or you suspect that you might have it not taking into account?
The Person object is "snapped" of the current RollbarConfig object associated with a Rollbar instance every time a Log(...) method is called. So, even you update either Person object or its properties later in the game, every subsequent call to Log(...) should "see" the updated Person object.

**Comment by buzzware** [comment]
Sorry, it turned out that the Serilog adapter I am using https://github.com/olsh/serilog-sinks-rollbar doesn't use RollbarLocator.RollbarInstance, and so I was configuring the wrong instance. You're right - Configure() doesn't need to do anything for Person because Person gets read every time. I ended up modifying the adapter to accept a Rollbar instance eg. RollbarLocator.RollbarInstance
