### ISSUE TITLE
Asp .Net Core 2.0.1 - RollbarMiddleware Issues

### ISSUE THREAD

**Issue by mike4299** [rollbar/Rollbar.NET#98]
Hey Everyone!

I created new asp .net core 2.0 project, and installed Rollbar package for Errors, But i couldn't get app.UseRollbarMiddleware; 
According to documentation as portion "ASP.NET Core 2" used Option Two.
Please suggest me whats problem about Middleware.

Thank you

**Comment by akornich** [comment]
@mike4299, what do you exactly mean by "i couldn't get app.UseRollbarMiddleware"?
Please, refer to this fully functional example of the middleware usage: [https://github.com/rollbar/Rollbar.NET/blob/master/Sample.AspNetCore2.WebApi/Startup.cs](url)

**Comment by mirza407** [comment]
@akornich  
in Startup.cs 
i couldn't get any nugut assembly reference to install this UseRollbarMiddleware()
please check my attachment.

Thank you
![rollbar](https://user-images.githubusercontent.com/20066703/37204071-a406f5dc-23b1-11e8-9b9a-e9fa9773665b.PNG)

**Comment by akornich** [comment]
@mirza407, did you install the Rollbar NuGet package?

**Comment by mirza407** [comment]
@akornich yes i installed Rollbar NuGet package first

**Comment by akornich** [comment]
@mirza407, Rollbar.NET v1.1.0 was just published. Please, update to the latest NuGet release, this may force the package manager cache refresh and hopefully solve the issue.

**Comment by akornich** [comment]
@mike4299 and @mirza407, is this still an issue or you did figure out what was wrong?

**Comment by akornich** [comment]
closing due to no repro and no responses.

**Comment by mirza407** [comment]
Thank you for your response and sorry for late reply,
Problem solved by using new version of Rollbar packages.
@akornich  @rivkahstandig3636

**Comment by akornich** [comment]
@mirza407, thanks for the update. i am glad it worked for you. btw, i noticed that last few minor updates to visual studio 2017 made the package manager very unreliable.  already multiple times odd packaging behaviour was sold by clearing the package manager cache, restarting visual studio and restoring the packages again.

**Comment by mirza407** [comment]
ok @akornich  by the way one thing i noticed that  " app.UseRollbarMiddleware(); " this line error fixed due to new version updating, but now due to this line " app.UseRollbarMiddleware(); ", .Net Core project not open in  browser just display me as This Site can't be reached.
So Whenever i commented this line "  app.UseRollbarMiddleware(); " then project run successfully.

So, whats you know about that ?
Thank you

**Comment by akornich** [comment]
@mirza407, are you getting any exceptions when you have UseRollbarMiddleware() call enabled?

**Comment by mirza407** [comment]
@akornich  if you are asking about rollbar exceptions dashboard then when i used UseRollbarMiddleware() then its just show this site can't reached on my browser 
and in Rollbar dashboard still displaying as "**We haven't received any data for this project yet.**" and i already followed all steps about .net core 2.0 in documentation, and add my rollbar server key in project.

**Comment by akornich** [comment]
@mirza407, what i mean is when you run your application under debugger, are you getting an exception during the UseRollbarMiddleware call?

**Comment by mirza407** [comment]
ohh this is output when used UseRollbarMiddleware, 
![capture](https://user-images.githubusercontent.com/20066703/38238205-9bae5598-3742-11e8-81e7-b946a0092051.PNG)

**Comment by akornich** [comment]
@mirza407, yes. can you, please, post the whole call stack which last line shows up at the top of the screenshot (as "at Microsoft....)?

**Comment by akornich** [comment]
@mirza407, also, please, make sure you have the Rollbar Logger service added in the way similar to this example:
Within the ConfigureServices(…) method of Startup.cs, add proper Rollbar configuration and register the Rollbar logger with the application services:

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            ConfigureRollbarSingleton();

            services.AddRollbarLogger(loggerOptions =>
            {
                loggerOptions.Filter = (loggerName, loglevel) => loglevel >= LogLevel.Trace;
            });
        
            services.AddMvc();
        }

        /// <summary>
        /// Configures the Rollbar singleton-like notifier.
        /// </summary>
        private void ConfigureRollbarSingleton()
        {
            const string rollbarAccessToken = "POST_SERVER_ITEM_ACCESS_TOKEN";
            const string rollbarEnvironment = "RollbarNetSamples";

            RollbarLocator.RollbarInstance
                // minimally required Rollbar configuration:
                .Configure(new RollbarConfig(rollbarAccessToken) { Environment = rollbarEnvironment })
                // optional step if you would like to monitor Rollbar internal events within your application:
                .InternalEvent += OnRollbarInternalEvent
                ;
        }

**Comment by mirza407** [comment]
@akornich  yes sure please check this out put when using app.UseRollbarMiddleware();
![rollbar2](https://user-images.githubusercontent.com/20066703/38295323-0f627dc4-3807-11e8-88c8-d10e903e5efd.PNG)

And i already followed all instructions to using .Net core 2.0 from docs 
As my code:

![rollbar](https://user-images.githubusercontent.com/20066703/38295380-3b0f7828-3807-11e8-9988-7544d59f5921.PNG)

Thank you
*everything is working fine when i just comment app.UseRollbarMiddleware(); line from configure

**Comment by akornich** [comment]
@mirza407, may i ask you get latest clone of rollbar.net from github, reference its project in your application (instead of nuget package) and do similar call stack capture of the exception for a debug build. also, please ctrl-a, ctrl-c the content of the output window/view as a text and paste it (not as a screen shot). thanks!

**Comment by michaellomonosov** [comment]
I have same problem. I tried  start with config file and in code like above mentioned posts. 
If I want start from config file, I correctly understand thant I need just write
```
public IServiceProvider ConfigureServices()
{...
services.AddRollbarLogger();
...
}
 public void Configure()
{
 app.UseRollbarMiddleware();
}
```
?

**Comment by michaellomonosov** [comment]
problem there are http://joxi.ru/l2ZnnRPSwpp482
HttpAttributes was set in middleware only. First calling of RollbarLogger was early when calling RollbarMiddleware Ivoke.
I fix on my local copy like this
 private RollbarHttpContext GetCurrentContext()
        {
            var temp = RollbarScope.Current?.HttpContext ?? new RollbarHttpContext();
            if (temp.HttpAttributes == null)
            {
                temp.HttpAttributes = new RollbarHttpAttributes(_httpContextAccessor.HttpContext);
            }
            return temp;
        }
and add injection for IHttpContextAccessor _httpContextAccessor to rollbarlogger, rollbarloggerprovaider and rollbarloggerfactory. 
Looking for stable release.

**Comment by akornich** [comment]
@michaellomonosov, correct. if you use the config file for Rollbar configuration, you do not need to do explicit configuration in code. when both (in-code and via config file) are used, the in-code version wins if it sets an access token, otherwise, the config file wins.

**Comment by akornich** [comment]
@michaellomonosov, thanks a lot for locating the exception source. I'll add the fix today and will probably publish a new release either today or tomorrow.
interesting that so far, i was not able to repro the problem using either our unit test or our sample test. my guess is, whoever can repro it probably uses either EF core or some other infrastructure component that uses asp.net core logger in relatively verbose mode during its initialization but before rollbar middleware is loaded/used.

**Comment by akornich** [comment]
@michaellomonosov and @mirza407, can you, guys, confirm that the fix i just pushed to my fork:
[https://github.com/WideSpectrumComputing/Rollbar.NET](url)
does completely resolve the issue you experience? Thanks!

**Comment by michaellomonosov** [comment]
@akornich rolled changes, yes it's work.

**Comment by akornich** [comment]
@mirza407 and @michaellomonosov, v1.2.0 is published on Nuget. Please, give it a try. This fix is in.
